// Package themes loads color-only palettes generated by theme-builder.
package themes

import (
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strings"

	"github.com/pelletier/go-toml/v2"
)

type Config struct {
	Mode  string `toml:"mode"`
	Light string `toml:"light"`
	Dark  string `toml:"dark"`
}

func (c Config) WithDefaults() Config {
	if c.Mode == "" {
		c.Mode = "auto"
	}
	if c.Light == "" {
		c.Light = "doric-marble"
	}
	if c.Dark == "" {
		c.Dark = "doric-obsidian"
	}
	return c
}

func (c Config) Validate() error {
	c = c.WithDefaults()
	if c.Mode != "auto" && c.Mode != "light" && c.Mode != "dark" {
		return fmt.Errorf("theme.mode must be auto, light, or dark (got %q)", c.Mode)
	}
	for _, name := range []string{c.Light, c.Dark} {
		if !namePattern.MatchString(name) {
			return fmt.Errorf("invalid Herdsman theme name %q: use lowercase letters, digits, and hyphens", name)
		}
	}
	return nil
}

// Name detects the background only in auto mode. The caller supplies terminal
// detection (including its dark fallback) so selection is independently testable.
func (c Config) Name(hasDarkBackground func() bool) string {
	c = c.WithDefaults()
	if c.Mode == "dark" || (c.Mode == "auto" && hasDarkBackground()) {
		return c.Dark
	}
	return c.Light
}

type Colors struct {
	Text                string `toml:"text"`
	Muted               string `toml:"muted"`
	Accent              string `toml:"accent"`
	SelectionBackground string `toml:"selection_background"`
	SelectionText       string `toml:"selection_text"`
	FilenameSecondary   string `toml:"filename_secondary"`
	FilenameMuted       string `toml:"filename_muted"`
	Match               string `toml:"match"`
	Error               string `toml:"error"`
}

var color = regexp.MustCompile(`^#[0-9a-fA-F]{6}$`)
var namePattern = regexp.MustCompile(`^[a-z0-9-]+$`)

// Load returns zero colors for an absent palette, selecting terminal-native
// styling. Present but unreadable or malformed files are configuration errors.
func Load(dir, name string) (Colors, error) {
	if !namePattern.MatchString(name) {
		return Colors{}, fmt.Errorf("invalid Herdsman theme name %q", name)
	}
	path := filepath.Join(dir, name+".toml")
	data, err := os.ReadFile(path)
	if os.IsNotExist(err) {
		// A dangling symlink is a present but unreadable palette, not an
		// intentionally absent one.
		if _, statErr := os.Lstat(path); os.IsNotExist(statErr) {
			return Colors{}, nil
		}
	}
	if err != nil {
		return Colors{}, fmt.Errorf("read theme %s: %w", path, err)
	}
	var palette struct {
		Colors Colors `toml:"colors"`
	}
	if err := toml.NewDecoder(strings.NewReader(string(data))).DisallowUnknownFields().Decode(&palette); err != nil {
		return Colors{}, fmt.Errorf("parse theme %q: %w", name, err)
	}
	c := palette.Colors
	// Older custom palettes remain valid; filename tones default to muted text.
	if c.FilenameSecondary == "" {
		c.FilenameSecondary = c.Muted
	}
	if c.FilenameMuted == "" {
		c.FilenameMuted = c.Muted
	}
	for _, value := range []string{c.Text, c.Muted, c.Accent, c.SelectionBackground, c.SelectionText, c.FilenameSecondary, c.FilenameMuted, c.Match, c.Error} {
		if !color.MatchString(value) {
			return Colors{}, fmt.Errorf("theme %q has a missing or invalid color", name)
		}
	}
	return c, nil
}
