;;; my-task-session-tests.el --- Tests for task session behavior -*- lexical-binding: t -*-

;;; Commentary:

;; Task session and active-session coverage.

;;; Code:

(require 'my-task-test-support)

(declare-function my/task-session-active-ids "my-task-session" ())
(declare-function my/task-session-applicable-agents-files "my-task-session" (worktree))
(declare-function my/task-session-bootstrap-context "my-task-session" (task &optional worktree))
(declare-function my/task-session-command-exit "my-task-session" (&optional task))
(declare-function my/task-session-command-pickup "my-task-session"
                  (&optional task &key launch-config advanced-options interactive-p))
(declare-function my/task-session-kill-orphaned-buffers "my-task-session" ())
(declare-function my/task-session-prepare-work-async "my-task-session"
                  (task-id &rest args))
(declare-function my/task-session-restore-view "my-task-session" (task))
(declare-function my/task-session-state-add "my-task-session" (task))
(declare-function my/task-session-state-remove "my-task-session" (task))
(declare-function my/task-session-sync-active "my-task-session" ())
(declare-function my/task-session-sync-entry "my-task-session" (task-id &optional session-buffer))

(ert-deftest my/task-session-state-remove-does-not-recreate-missing-entry ()
  (my/task-index-test--with-isolated-index
    (let ((task-id "20260324T082727"))
      (puthash task-id (my/task-index-test--entry task-id :worktree "/tmp/a/") my/task-index)
      (cl-letf (((symbol-function 'my/task-resolve-id) (lambda (task) task))
                ((symbol-function 'my/task-state-notify) (lambda (&rest _) nil)))
        (provide 'consult)
        (require 'my-task-session)
        (remhash task-id my/task-index)
        (my/task-session-state-remove task-id)
        (should-not (gethash task-id my/task-index))))))

(ert-deftest my/task-session-state-add-marks-session-active ()
  (provide 'consult)
  (require 'my-task-session)
  (let (active-calls)
    (cl-letf (((symbol-function 'my/task-resolve-id) (lambda (task) task))
              ((symbol-function 'my/task-session-active-set)
               (lambda (task active)
                 (push (list task active) active-calls))))
      (my/task-session-state-add "without-skill")
      (my/task-session-state-add "with-skill")
      (should (equal (nreverse active-calls)
                     '(("without-skill" t)
                       ("with-skill" t)))))))

(ert-deftest my/task-session-bootstrap-context-uses-public-task-apis ()
  (provide 'consult)
  (require 'my-task-session)
  (cl-letf (((symbol-function 'my/task-resolve-id)
             (lambda (_task)
               "20260324T082727"))
            ((symbol-function 'my/task-file)
             (lambda (_task-id)
               "/tmp/task.md"))
            ((symbol-function 'denote-filetype-heuristics)
             (lambda (_file)
               'markdown-yaml))
            ((symbol-function 'denote-retrieve-front-matter-title-value)
             (lambda (_file _filetype)
               "Bump Nix"))
            ((symbol-function 'denote-retrieve-filename-title)
             (lambda (_file)
               (ert-fail "front matter title should win")))
            ((symbol-function 'my/task-skill)
             (lambda (_task)
               "bump-nix"))
            ((symbol-function 'my/task-note-content)
             (lambda (_task)
               "## Context\n\nBump Nix."))
            ((symbol-function 'my/task-session-applicable-agents-files)
             (lambda (_worktree)
               '("/Users/jamesl/work/AGENTS.md"
                 "/Users/jamesl/work/brucenunk/AGENTS.md"
                 "/Users/jamesl/work/brucenunk/home-config/c/AGENTS.md"))))
    (should (equal (my/task-session-bootstrap-context
                    "/tmp/task.md"
                    "/Users/jamesl/work/brucenunk/home-config/c")
                   '(:task-id "20260324T082727"
                     :title "Bump Nix"
                     :skill "bump-nix"
                     :task-note-content "## Context\n\nBump Nix."
                     :agents-files
                     ("/Users/jamesl/work/AGENTS.md"
                      "/Users/jamesl/work/brucenunk/AGENTS.md"
                      "/Users/jamesl/work/brucenunk/home-config/c/AGENTS.md"))))))

(ert-deftest my/task-session-bootstrap-context-includes-note-content-without-front-matter ()
  (provide 'consult)
  (require 'my-task-session)
  (let ((task-file (make-temp-file "my-task-bootstrap" nil ".md"
                                   (concat
                                    "---\n"
                                    "title: Test task\n"
                                    "skill: task-workflow-v3\n"
                                    "---\n\n"
                                    "## Context\n\n"
                                    "Body text.\n"))))
    (unwind-protect
        (cl-letf (((symbol-function 'my/task-resolve-id)
                   (lambda (_task)
                     "20260324T082727"))
                  ((symbol-function 'my/task-file)
                   (lambda (_task-id)
                     task-file))
                  ((symbol-function 'denote-filetype-heuristics)
                   (lambda (_file)
                     'markdown-yaml))
                  ((symbol-function 'denote-retrieve-front-matter-title-value)
                   (lambda (_file _filetype)
                     "Test task"))
                  ((symbol-function 'my/task-session-applicable-agents-files)
                   (lambda (_worktree)
                     nil)))
          (should (equal (my/task-session-bootstrap-context task-file)
                         '(:task-id "20260324T082727"
                           :title "Test task"
                           :skill "task-workflow-v3"
                           :task-note-content "## Context\n\nBody text.\n"
                           :agents-files nil))))
      (delete-file task-file t))))

(ert-deftest my/task-session-bootstrap-context-without-skill-keeps-agents-files ()
  (provide 'consult)
  (require 'my-task-session)
  (cl-letf (((symbol-function 'my/task-resolve-id)
             (lambda (_task)
               "20260324T082728"))
            ((symbol-function 'my/task-file)
             (lambda (_task-id)
               "/tmp/task.md"))
            ((symbol-function 'denote-filetype-heuristics)
             (lambda (_file)
               'markdown-yaml))
            ((symbol-function 'denote-retrieve-front-matter-title-value)
             (lambda (_file _filetype)
               "Generic task"))
            ((symbol-function 'denote-retrieve-filename-title)
             (lambda (_file)
               (ert-fail "front matter title should win")))
            ((symbol-function 'my/task-skill)
             (lambda (_task)
               nil))
            ((symbol-function 'my/task-note-content)
             (lambda (_task)
               "## Context\n\nGeneric task body."))
            ((symbol-function 'my/task-session-applicable-agents-files)
             (lambda (_worktree)
               '("/Users/jamesl/work/AGENTS.md"
                 "/Users/jamesl/work/brucenunk/AGENTS.md"))))
    (should (equal (my/task-session-bootstrap-context
                    "/tmp/task.md"
                    "/Users/jamesl/work/brucenunk/home-config/c")
                   '(:task-id "20260324T082728"
                     :title "Generic task"
                     :skill nil
                     :task-note-content "## Context\n\nGeneric task body."
                     :agents-files
                     ("/Users/jamesl/work/AGENTS.md"
                      "/Users/jamesl/work/brucenunk/AGENTS.md"))))))

(ert-deftest my/task-session-bootstrap-context-without-agents-files-falls-back-cleanly ()
  (provide 'consult)
  (require 'my-task-session)
  (cl-letf (((symbol-function 'my/task-resolve-id)
             (lambda (_task)
               "20260324T082729"))
            ((symbol-function 'my/task-file)
             (lambda (_task-id)
               "/tmp/task.md"))
            ((symbol-function 'denote-filetype-heuristics)
             (lambda (_file)
               'markdown-yaml))
            ((symbol-function 'denote-retrieve-front-matter-title-value)
             (lambda (_file _filetype)
               "Fallback task"))
            ((symbol-function 'denote-retrieve-filename-title)
             (lambda (_file)
               (ert-fail "front matter title should win")))
            ((symbol-function 'my/task-skill)
             (lambda (_task)
               "bump-nix"))
            ((symbol-function 'my/task-note-content)
             (lambda (_task)
               "## Context\n\nFallback body."))
            ((symbol-function 'my/task-session-applicable-agents-files)
             (lambda (_worktree)
               nil)))
    (should (equal (my/task-session-bootstrap-context
                    "/tmp/task.md"
                    "/Users/jamesl/work/brucenunk/home-config/c")
                   '(:task-id "20260324T082729"
                     :title "Fallback task"
                     :skill "bump-nix"
                     :task-note-content "## Context\n\nFallback body."
                     :agents-files nil)))))

(ert-deftest my/task-session-applicable-agents-files-walks-to-work-root ()
  (provide 'consult)
  (require 'my-task-session)
  (cl-letf (((symbol-function 'expand-file-name)
             (lambda (path &optional dir)
               (cond
                ((equal path "~/work")
                 "/Users/jamesl/work")
                (dir
                 (concat (file-name-as-directory dir) path))
                (t path))))
            ((symbol-function 'file-exists-p)
             (lambda (path)
               (member path '("/Users/jamesl/work/AGENTS.md"
                              "/Users/jamesl/work/brucenunk/AGENTS.md"
                              "/Users/jamesl/work/brucenunk/home-config/c/AGENTS.md")))))
    (should (equal (my/task-session-applicable-agents-files
                    "/Users/jamesl/work/brucenunk/home-config/c")
                   '("/Users/jamesl/work/AGENTS.md"
                     "/Users/jamesl/work/brucenunk/AGENTS.md"
                     "/Users/jamesl/work/brucenunk/home-config/c/AGENTS.md")))))

(ert-deftest my/task-session-bootstrap-context-without-skill-uses-generic-metadata ()
  (provide 'consult)
  (require 'my-task-session)
  (cl-letf (((symbol-function 'my/task-resolve-id)
             (lambda (_task)
               "20260324T082727"))
            ((symbol-function 'my/task-file)
             (lambda (_task-id)
               "/tmp/task.md"))
            ((symbol-function 'denote-filetype-heuristics)
             (lambda (_file)
               'markdown-yaml))
            ((symbol-function 'denote-retrieve-front-matter-title-value)
             (lambda (_file _filetype)
               "Quick note"))
            ((symbol-function 'my/task-skill)
             (lambda (_task)
               nil))
            ((symbol-function 'my/task-note-content)
             (lambda (_task)
               "## Context\n\nQuick note body.")))
    (should (equal (my/task-session-bootstrap-context "/tmp/task.md")
                   '(:task-id "20260324T082727"
                     :title "Quick note"
                     :skill nil
                     :task-note-content "## Context\n\nQuick note body."
                     :agents-files nil)))))

(ert-deftest my/task-session-active-ids-skips-global-repair ()
  (provide 'consult)
  (require 'my-task-session)
  (let ((sync-called nil))
    (cl-letf (((symbol-function 'my/task--repair-index)
               (lambda ()
                 (ert-fail "global repair should not run on active-session lookup")))
              ((symbol-function 'my/task-session-sync-active)
               (lambda ()
                 (setq sync-called t)
                 '("20260324T082727")))
              ((symbol-function 'my/task-index-entries-where)
               (lambda (_prop _value)
                 (list (list :task-id "20260324T082727" :active t)
                       (list :task-id "20260324T082728" :active t)))))
      (should (equal (my/task-session-active-ids)
                     '("20260324T082727" "20260324T082728")))
      (should sync-called))))

(ert-deftest my/task-session-active-ids-clears-stale-active-entry-without-global-repair ()
  (my/task-index-test--with-isolated-index
    (provide 'consult)
    (require 'my-task-session)
    (let ((task-id "20260324T082727")
          notifications)
      (puthash task-id
               (my/task-index-test--entry task-id :worktree "/tmp/a/" :active t)
               my/task-index)
      (cl-letf (((symbol-function 'my/task--repair-index)
                 (lambda ()
                   (ert-fail "global repair should not run on active-session lookup")))
                ((symbol-function 'my/task-file)
                 (lambda (_task-id)
                   "/tmp/task.md"))
                ((symbol-function 'my/task-status)
                 (lambda (_task)
                   "todo"))
                ((symbol-function 'my/task-session-live-buffer)
                 (lambda (_task-id)
                   nil))
                ((symbol-function 'my/task-state-notify)
                 (lambda (&rest args)
                   (push args notifications))))
        (should-not (my/task-session-active-ids))
        (should-not (plist-get (gethash task-id my/task-index) :active))
        (should (= (length notifications) 1))
        (should-not (plist-get (nthcdr 2 (car notifications)) :active))))))

(ert-deftest my/task-session-sync-active-prunes-live-stale-session ()
  (my/task-index-test--with-isolated-index
    (provide 'consult)
    (require 'my-task-session)
    (let ((task-id "20260324T082727")
          pruned)
      (puthash task-id
               (my/task-index-test--entry task-id :worktree "/tmp/a/" :active t)
               my/task-index)
      (with-temp-buffer
        (rename-buffer (format "agent-task-%s" task-id) t)
        (setq-local my/task-session-task-id task-id)
        (cl-letf (((symbol-function 'my/agent-session-live-p)
                   (lambda (_buffer)
                     t))
                  ((symbol-function 'my/task-session-sync-entry)
                   (lambda (&rest _) nil))
                  ((symbol-function 'my/task-session-stale-reason)
                   (lambda (_task-id &optional _entry)
                     'missing-worktree))
                  ((symbol-function 'my/task-session-prune-stale)
                   (lambda (id reason)
                     (push (list id reason) pruned))))
          (should (equal (my/task-session-sync-active) (list task-id)))
          (should (equal pruned
                         (list (list task-id 'missing-worktree)))))))))

(ert-deftest my/task-session-sync-active-keeps-live-session-with-shared-task-root ()
  (my/task-index-test--with-isolated-index
    (provide 'consult)
    (require 'my-task-session)
    (let* ((temp-root (make-temp-file "my-task-session-shared-root" t))
           (tasks-root (expand-file-name "tasks/" temp-root))
           (epic-dir (expand-file-name "session-bugs/" tasks-root))
           (task-id "20260324T082727")
           (task-file (expand-file-name
                       (format "%s==todo--shared-root-live-session.md" task-id)
                       epic-dir))
           (my/task--file-cache (make-hash-table :test 'equal)))
      (make-directory epic-dir t)
      (unwind-protect
          (progn
            (with-temp-file task-file
              (insert "---\n---\n"))
            (puthash task-id
                     (my/task-index-test--entry task-id :worktree "/tmp/a/" :active t)
                     my/task-index)
            (with-temp-buffer
              (rename-buffer (format "agent-task-%s" task-id) t)
              (setq default-directory "/tmp/a/")
              (setq-local my/task-session-task-id task-id)
              (let ((denote-directory tasks-root))
                (cl-letf (((symbol-function 'my/agent-session-live-p)
                           (lambda (_buffer)
                             t))
                          ((symbol-function 'my/task--task-directories)
                           (lambda ()
                             (list tasks-root)))
                          ((symbol-function 'denote-get-path-by-id) (lambda (_id) nil))
                          ((symbol-function 'denote-retrieve-filename-signature)
                           (lambda (file)
                             (should (equal file task-file))
                             "todo"))
                          ((symbol-function 'my/task-session-prune-stale)
                           (lambda (&rest _args)
                             (ert-fail "Shared-root resolution should keep the live session active"))))
                  (should (equal (my/task-session-sync-active) (list task-id)))
                  (should (plist-get (gethash task-id my/task-index) :active))))))
        (delete-directory temp-root t)))))

(ert-deftest my/task-session-current-title-falls-back-across-shared-task_root ()
  (provide 'consult)
  (require 'my-task-session)
  (let* ((temp-root (make-temp-file "my-task-session-title" t))
         (tasks-root (expand-file-name "tasks/" temp-root))
         (epic-dir (expand-file-name "session-bugs/" tasks-root))
         (task-id "20260324T082727")
         (task-file (expand-file-name
                     (format "%s==todo--shared-root-title.md" task-id)
                     epic-dir))
         (my/task--file-cache (make-hash-table :test 'equal)))
    (make-directory epic-dir t)
    (unwind-protect
        (progn
          (with-temp-file task-file
            (insert "---\n---\n"))
          (with-temp-buffer
            (setq-local my/task-session-task-id task-id)
            (let ((denote-directory tasks-root))
              (cl-letf (((symbol-function 'my/task--task-directories)
                         (lambda ()
                           (list tasks-root)))
                        ((symbol-function 'denote-get-path-by-id) (lambda (_id) nil))
                        ((symbol-function 'denote-filetype-heuristics)
                         (lambda (_file)
                           'markdown-yaml))
                        ((symbol-function 'denote-retrieve-title-value)
                         (lambda (file _file-type)
                           (when (equal file task-file)
                             "Shared root title"))))
                (should (equal (my/task-session-current-title)
                               "Shared root title"))))))
      (delete-directory temp-root t))))

(ert-deftest my/task-session-title-from-path-uses-index-only-without-git-fallback ()
  (provide 'consult)
  (require 'my-task-session)
  (let ((task-id "20260324T082727")
        (task-file "/tmp/20260324T082727==todo--task.md"))
    (cl-letf (((symbol-function 'my/task-index-find-by-worktree)
               (lambda (path)
                 (should (equal path "/Users/jamesl/work/brucenunk/home-config/b/"))
                 task-id))
              ((symbol-function 'my/task-note-file)
               (lambda (id)
                 (should (equal id task-id))
                 task-file))
              ((symbol-function 'my/task-note-title)
               (lambda (file)
                 (should (equal file task-file))
                 "Indexed task title"))
              ((symbol-function 'my/task-find-by-worktree)
               (lambda (&rest _args)
                 (ert-fail "title lookup should not fall back to git-backed task resolution"))))
      (with-temp-buffer
        (rename-buffer "buffer-fallback" t)
        (should (equal (my/task-session-title-from-path
                        "/Users/jamesl/work/brucenunk/home-config/b/config/emacs/init.el")
                       "Indexed task title"))))))

(ert-deftest my/task-session-title-from-path-falls-back-to-buffer-name-when-unindexed ()
  (provide 'consult)
  (require 'my-task-session)
  (let (queued-worktree)
    (cl-letf (((symbol-function 'my/task-index-find-by-worktree)
               (lambda (_path) nil))
              ((symbol-function 'my/task-session--queue-title-backfill)
               (lambda (worktree-path)
                 (setq queued-worktree worktree-path)))
              ((symbol-function 'my/task-find-by-worktree)
               (lambda (&rest _args)
                 (ert-fail "title lookup should not use git-backed fallback when unindexed"))))
      (with-temp-buffer
        (rename-buffer "buffer-fallback" t)
        (should (equal (my/task-session-title-from-path
                        "/Users/jamesl/work/brucenunk/home-config/b/config/emacs/init.el")
                       "buffer-fallback"))
        (should (equal queued-worktree
                       "/Users/jamesl/work/brucenunk/home-config/b/"))))))

(ert-deftest my/task-session-queue-title-backfill-populates-transient-worktree-state ()
  (provide 'consult)
  (require 'my-task-session)
  (let ((task-id "20260414T215613")
        recorded-worktree
        notifications)
    (clrhash my/task-session--title-backfill-pending)
    (cl-letf (((symbol-function 'my/git-run-async)
               (lambda (_dir _args &rest plist)
                 (funcall (plist-get plist :on-success)
                          "jamesl-20260414T215613\n" 0)))
              ((symbol-function 'my/task--feature-worktree-p)
               (lambda (_path) t))
              ((symbol-function 'my/task-session--call-repair)
               (lambda (_fn branch)
                 (should (equal branch "jamesl-20260414T215613"))
                 task-id))
              ((symbol-function 'my/task-note-file)
               (lambda (id)
                 (should (equal id task-id))
                 "/tmp/task.md"))
              ((symbol-function 'my/task-note-status)
               (lambda (file)
                 (should (equal file "/tmp/task.md"))
                 "todo"))
              ((symbol-function 'my/task-index-worktree-set)
               (lambda (id worktree &optional _persist)
                 (should (equal id task-id))
                 (setq recorded-worktree worktree)))
              ((symbol-function 'my/task-state-notify)
               (lambda (id source &rest props)
                 (push (list id source props) notifications))))
      (my/task-session--queue-title-backfill "/Users/jamesl/work/brucenunk/home-config/b/")
      (should (equal recorded-worktree
                     "/Users/jamesl/work/brucenunk/home-config/b/"))
      (should (equal (caar notifications) task-id))
      (should-not (gethash "/Users/jamesl/work/brucenunk/home-config/b/"
                           my/task-session--title-backfill-pending)))))

(ert-deftest my/task-session-queue-title-backfill-ignores-default-worktree-paths ()
  (provide 'consult)
  (require 'my-task-session)
  (clrhash my/task-session--title-backfill-pending)
  (cl-letf (((symbol-function 'my/task--feature-worktree-p)
             (lambda (_path) nil))
            ((symbol-function 'my/git-run-async)
             (lambda (&rest _args)
               (ert-fail "default worktree paths should not trigger title backfill"))))
    (my/task-session--queue-title-backfill "/Users/jamesl/work/brucenunk/home-config/main/")
    (should (zerop (hash-table-count my/task-session--title-backfill-pending)))))

(ert-deftest my/task-session-sync-entry-does-not-resolve-task-file ()
  (my/task-index-test--with-isolated-index
    (provide 'consult)
    (require 'my-task-session)
    (let ((task-id "20260324T082727")
          notifications)
      (puthash task-id
               (my/task-index-test--entry task-id :worktree "/tmp/old/")
               my/task-index)
      (with-temp-buffer
        (setq default-directory "/tmp/new/")
        (cl-letf (((symbol-function 'my/task-file)
                   (lambda (&rest _)
                     (ert-fail "sync hot path should not resolve the task note")))
                  ((symbol-function 'my/task-state-notify)
                   (lambda (&rest args)
                     (push args notifications))))
          (my/task-session-sync-entry task-id (current-buffer))))
      (should (equal (plist-get (gethash task-id my/task-index) :worktree)
                     "/tmp/new/"))
      (should (= (length notifications) 1)))))

(ert-deftest my/task-session-sync-entry-backfills-worktree-from-session-buffer ()
  (my/task-index-test--with-isolated-index
    (provide 'consult)
    (require 'my-task-session)
    (let ((task-id "20260324T082728")
          notifications)
      (with-temp-buffer
        (setq default-directory "/Users/jamesl/work/brucenunk/home-config/g/")
        (cl-letf (((symbol-function 'my/task-state-notify)
                   (lambda (&rest args)
                     (push args notifications)))
                  ((symbol-function 'my/task-file)
                   (lambda (&rest _)
                     (ert-fail "sync hot path should not resolve the task note"))))
          (my/task-session-sync-entry task-id (current-buffer))))
      (let ((entry (gethash task-id my/task-index)))
        (should (equal (plist-get entry :worktree)
                       "/Users/jamesl/work/brucenunk/home-config/g/")))
      (should (equal notifications
                     '(("20260324T082728"
                         session
                         :changes (:worktree)
                         :worktree "/Users/jamesl/work/brucenunk/home-config/g/")))))))

(ert-deftest my/task-session-prepare-work-async-persists-worktree-on-assignment ()
  (provide 'consult)
  (require 'my-task-session)
  (require 'my-worktree-repair)
  (let (recorded-put)
    (cl-letf (((symbol-function 'denote-get-path-by-id)
               (lambda (_task-id)
                 "/tmp/task.md"))
              ((symbol-function 'my/task-note-status)
               (lambda (_task)
                 "todo"))
              ((symbol-function 'my/task-note-owner-repo)
               (lambda (_task)
                 '("brucenunk" . "home-config")))
              ((symbol-function 'my/task-branch)
               (lambda (task-id)
                 (format "jamesl-%s" task-id)))
              ((symbol-function 'my/worktree-repair-entry-for-pickup)
               (lambda (_task-id)
                 nil))
              ((symbol-function 'my/worktree-repair-claimed-worktrees-for-pickup)
               (lambda ()
                 '()))
              ((symbol-function 'my/task-session-branch-exists-p)
               (lambda (&rest _args)
                 nil))
              ((symbol-function 'my/task-index-worktree-set)
               (lambda (task-id worktree &optional _persist)
                 (setq recorded-put (list task-id worktree))))
              ((symbol-function 'my/task-state-notify)
               (lambda (&rest _args)
                 nil))
              ((symbol-function 'my/hephaestus-allocate-async)
               (lambda (_owner _repo _branch &rest args)
                 (should (plist-get args :fetch))
                 (funcall (plist-get args :on-success) "/tmp/f/")))
              ((symbol-function 'my/task-session-reset-wip)
               (lambda (task-id worktree)
                 (should (equal task-id "20260324T103418"))
                 (should (equal worktree "/tmp/f/"))
                 t))
      (my/task-session-prepare-work-async
       "20260324T103418"
       :on-success (lambda (_result) nil)
       :on-error (lambda (err-msg)
                   (ert-fail err-msg)))
      (should (equal recorded-put
                     '("20260324T103418" "/tmp/f/"))))))

(ert-deftest my/task-session-prepare-work-async-prefers-recorded-pi-worktree-slot ()
  (provide 'consult)
  (require 'my-task-session)
  (let (setup-args success-result)
    (cl-letf (((symbol-function 'denote-get-path-by-id)
               (lambda (_task-id)
                 "/tmp/task.md"))
              ((symbol-function 'my/task-status)
               (lambda (_task)
                 "todo"))
              ((symbol-function 'my/task-owner-repo)
               (lambda (_task)
                 '("brucenunk" . "home-config")))
              ((symbol-function 'my/task-branch)
               (lambda (task-id)
                 (format "jamesl-%s" task-id)))
              ((symbol-function 'my/worktree-repair-claimed-worktrees-for-pickup)
               (lambda ()
                 '()))
              ((symbol-function 'my/task-note-worktree-get)
               (lambda (_task-id)
                 "c"))
              ((symbol-function 'my/worktree-list-for-repo)
               (lambda (_owner _repo)
                 '((:path "/tmp/c/" :branch nil :detached t)
                   (:path "/tmp/d/" :branch nil :detached t))))
              ((symbol-function 'my/worktree-clean-p)
               (lambda (_path)
                 t))
              ((symbol-function 'my/task-worktree)
               (lambda (_task-id)
                 nil))
              ((symbol-function 'my/task-index-find-by-worktree)
               (lambda (_path)
                 nil))
              ((symbol-function 'my/task-index-worktree-set)
               (lambda (&rest _args)
                 nil))
              ((symbol-function 'my/task-state-notify)
               (lambda (&rest _args)
                 nil))
              ((symbol-function 'my/task-session-branch-exists-p)
               (lambda (&rest _args)
                 nil))
              ((symbol-function 'my/task-session-setup-worktree-async)
               (lambda (worktree-path _task-id &rest args)
                 (setq setup-args (cons worktree-path args))
                 (funcall (plist-get args :on-success) "jamesl-20260324T103418")))
              ((symbol-function 'my/hephaestus-allocate-async)
               (lambda (&rest _args)
                 (ert-fail "recorded Pi worktree should bypass generic allocation"))))
      (my/task-session-prepare-work-async
       "20260324T103418"
       :resume-state '(:backend "pi" :id "20260422T031929929Z")
       :on-success (lambda (result)
                     (setq success-result result))
       :on-error (lambda (err-msg)
                   (ert-fail err-msg)))
      (should (equal (car setup-args) "/tmp/c/"))
      (should (equal (plist-get success-result :worktree) "/tmp/c/")))))

(ert-deftest my/task-session-prepare-work-async-errors-when-recorded-pi-worktree-is-missing ()
  (provide 'consult)
  (require 'my-task-session)
  (let (error-result)
    (cl-letf (((symbol-function 'denote-get-path-by-id)
               (lambda (_task-id)
                 "/tmp/task.md"))
              ((symbol-function 'my/task-status)
               (lambda (_task)
                 "todo"))
              ((symbol-function 'my/task-owner-repo)
               (lambda (_task)
                 '("brucenunk" . "home-config")))
              ((symbol-function 'my/task-branch)
               (lambda (task-id)
                 (format "jamesl-%s" task-id)))
              ((symbol-function 'my/worktree-repair-claimed-worktrees-for-pickup)
               (lambda ()
                 '()))
              ((symbol-function 'my/task-note-worktree-get)
               (lambda (_task-id)
                 nil))
              ((symbol-function 'my/task-worktree)
               (lambda (_task-id)
                 nil)))
      (my/task-session-prepare-work-async
       "20260324T103418"
       :resume-state '(:backend "pi" :id "20260422T031929929Z")
       :on-success (lambda (_result)
                     (ert-fail "Pi resume without recorded worktree should fail"))
       :on-error (lambda (err-msg)
                   (setq error-result err-msg)))
      (should (equal error-result
                     "Recorded Pi worktree is missing for task 20260324T103418")))))
(ert-deftest my/task-session-prepare-work-async-reuses-live-task-worktree ()
  (provide 'consult)
  (require 'my-task-session)
  (let (success-result error-result)
    (cl-letf (((symbol-function 'denote-get-path-by-id)
               (lambda (_task-id)
                 "/tmp/task.md"))
              ((symbol-function 'my/task-status)
               (lambda (_task)
                 "todo"))
              ((symbol-function 'my/task-owner-repo)
               (lambda (_task)
                 '("brucenunk" . "home-config")))
              ((symbol-function 'my/task-branch)
               (lambda (task-id)
                 (format "jamesl-%s" task-id)))
              ((symbol-function 'my/worktree-repair-claimed-worktrees-for-pickup)
               (lambda ()
                 '()))
              ((symbol-function 'my/task-worktree)
               (lambda (_task-id)
                 "/tmp/a/")))
      (my/task-session-prepare-work-async
       "20260324T103418"
       :on-success (lambda (result)
                     (setq success-result result))
       :on-error (lambda (err-msg)
                   (setq error-result err-msg)))
      (should-not error-result)
      (should (equal (plist-get success-result :worktree) "/tmp/a/"))
      (should (equal (plist-get success-result :task-id) "20260324T103418")))))

(ert-deftest my/task-session-prepare-work-async-reuses-existing-live-worktree-without-setup ()
  (provide 'consult)
  (require 'my-task-session)
  (let (success-result setup-called resume-called)
    (cl-letf (((symbol-function 'denote-get-path-by-id)
               (lambda (_task-id)
                 "/tmp/task.md"))
              ((symbol-function 'my/task-status)
               (lambda (_task)
                 "todo"))
              ((symbol-function 'my/task-owner-repo)
               (lambda (_task)
                 '("brucenunk" . "home-config")))
              ((symbol-function 'my/task-branch)
               (lambda (task-id)
                 (format "jamesl-%s" task-id)))
              ((symbol-function 'my/worktree-repair-claimed-worktrees-for-pickup)
               (lambda ()
                 '()))
              ((symbol-function 'my/task-worktree)
               (lambda (_task-id)
                 "/tmp/b/"))
              ((symbol-function 'my/task-session-setup-worktree-async)
               (lambda (&rest _args)
                 (setq setup-called t)))
              ((symbol-function 'my/task-session-resume-on-branch-async)
               (lambda (&rest _args)
                 (setq resume-called t))))
      (my/task-session-prepare-work-async
       "20260324T103418"
       :on-success (lambda (result)
                     (setq success-result result))
       :on-error (lambda (err-msg)
                   (ert-fail err-msg)))
      (should-not setup-called)
      (should-not resume-called)
      (should (equal (plist-get success-result :worktree) "/tmp/b/"))
      (should (equal (plist-get success-result :task-id) "20260324T103418")))))

(ert-deftest my/task-session-prepare-work-async-caches-existing-live-worktree-transiently ()
  (provide 'consult)
  (require 'my-task-session)
  (let (recorded-put success-result)
    (cl-letf (((symbol-function 'denote-get-path-by-id)
               (lambda (_task-id)
                 "/tmp/task.md"))
              ((symbol-function 'my/task-status)
               (lambda (_task)
                 "todo"))
              ((symbol-function 'my/task-owner-repo)
               (lambda (_task)
                 '("brucenunk" . "home-config")))
              ((symbol-function 'my/task-branch)
               (lambda (task-id)
                 (format "jamesl-%s" task-id)))
              ((symbol-function 'my/worktree-repair-claimed-worktrees-for-pickup)
               (lambda ()
                 '()))
              ((symbol-function 'my/task-worktree)
               (lambda (_task-id)
                 "/tmp/b/"))
              ((symbol-function 'my/task-index-worktree-set)
               (lambda (task-id worktree &optional _persist)
                 (setq recorded-put (list task-id worktree)))))
      (my/task-session-prepare-work-async
       "20260324T103418"
       :on-success (lambda (result)
                     (setq success-result result))
       :on-error (lambda (err-msg)
                   (ert-fail err-msg)))
      (should (equal recorded-put '("20260324T103418" "/tmp/b/")))
      (should (equal (plist-get success-result :worktree) "/tmp/b/"))
      (should (equal (plist-get success-result :task-id) "20260324T103418")))))

(ert-deftest my/task-session-prepare-work-async-recomputes-existing-worktree-after-claim-prune ()
  (provide 'consult)
  (require 'my-task-session)
  (let (success-result pruned recorded-put)
    (cl-letf (((symbol-function 'denote-get-path-by-id)
               (lambda (_task-id)
                 "/tmp/task.md"))
              ((symbol-function 'my/task-status)
               (lambda (_task)
                 "todo"))
              ((symbol-function 'my/task-owner-repo)
               (lambda (_task)
                 '("brucenunk" . "home-config")))
              ((symbol-function 'my/task-branch)
               (lambda (task-id)
                 (format "jamesl-%s" task-id)))
              ((symbol-function 'my/worktree-repair-claimed-worktrees-for-pickup)
               (lambda ()
                 (setq pruned t)
                 '()))
              ((symbol-function 'my/task-worktree)
               (lambda (_task-id)
                 (should pruned)
                 "/tmp/live/"))
              ((symbol-function 'my/task-index-worktree-set)
               (lambda (task-id worktree &optional _persist)
                 (setq recorded-put (list task-id worktree)))))
      (my/task-session-prepare-work-async
       "20260324T103418"
       :on-success (lambda (result)
                     (setq success-result result))
       :on-error (lambda (err-msg)
                   (ert-fail err-msg)))
      (should (equal recorded-put '("20260324T103418" "/tmp/live/")))
      (should (equal (plist-get success-result :worktree) "/tmp/live/")))))

(ert-deftest my/task-session-prepare-work-async-skips-dirty-unclaimed-worktree ()
  (provide 'consult)
  (require 'my-task-session)
  (let (success-result setup-args)
    (cl-letf (((symbol-function 'denote-get-path-by-id)
               (lambda (_task-id)
                 "/tmp/task.md"))
              ((symbol-function 'my/task-status)
               (lambda (_task)
                 "todo"))
              ((symbol-function 'my/task-owner-repo)
               (lambda (_task)
                 '("brucenunk" . "home-config")))
              ((symbol-function 'my/task-branch)
               (lambda (task-id)
                 (format "jamesl-%s" task-id)))
              ((symbol-function 'my/worktree-repair-claimed-worktrees-for-pickup)
               (lambda ()
                 '()))
              ((symbol-function 'my/task-worktree)
               (lambda (_task-id)
                 nil))
              ((symbol-function 'my/task-session-branch-exists-p)
               (lambda (&rest _args)
                 nil))
              ((symbol-function 'my/task-index-worktree-set)
               (lambda (&rest _args)
                 nil))
              ((symbol-function 'my/task-state-notify)
               (lambda (&rest _args)
                 nil))
              ((symbol-function 'my/hephaestus-allocate-async)
               (lambda (_owner _repo _branch &rest args)
                 (setq setup-args args)
                 (funcall (plist-get args :on-success) "/tmp/f/")))
              ((symbol-function 'my/task-session-reset-wip)
               (lambda (task-id worktree)
                 (should (equal task-id "20260324T103418"))
                 (should (equal worktree "/tmp/f/"))
                 t)))
      (my/task-session-prepare-work-async
       "20260324T103418"
       :on-success (lambda (result)
                     (setq success-result result))
       :on-error (lambda (err-msg)
                   (ert-fail err-msg)))
      (should-not (plist-get setup-args :worktree))
      (should (plist-get setup-args :fetch))
      (should (equal (plist-get success-result :worktree) "/tmp/f/")))))
(ert-deftest my/task-session-prepare-work-async-reports-dirty-worktrees-when-blocked ()
  (provide 'consult)
  (require 'my-task-session)
  (require 'my-worktree-repair)
  (let (error-result)
    (cl-letf (((symbol-function 'denote-get-path-by-id)
               (lambda (_task-id)
                 "/tmp/task.md"))
              ((symbol-function 'my/task-note-status)
               (lambda (_task-file)
                 "todo"))
              ((symbol-function 'my/task-note-owner-repo)
               (lambda (_task-file)
                 '("brucenunk" . "home-config")))
              ((symbol-function 'my/task-branch)
               (lambda (task-id)
                 (format "jamesl-%s" task-id)))
              ((symbol-function 'my/worktree-repair-entry-for-pickup)
               (lambda (_task-id)
                 nil))
              ((symbol-function 'my/worktree-repair-claimed-worktrees-for-pickup)
               (lambda ()
                 '()))
              ((symbol-function 'my/task-session-branch-exists-p)
               (lambda (&rest _args)
                 nil))
              ((symbol-function 'my/hephaestus-allocate-async)
               (lambda (&rest args)
                 (should (plist-get args :fetch))
                 (funcall (plist-get args :on-error)
                          "detached worktree is dirty and blocks allocation: /tmp/e/"))))
      (my/task-session-prepare-work-async
       "20260324T103418"
       :on-success (lambda (_result)
                     (ert-fail "pickup should not succeed"))
       :on-error (lambda (err-msg)
                   (setq error-result err-msg)))
      (should (equal error-result
                     "detached worktree is dirty and blocks allocation: /tmp/e/"))))))

(ert-deftest my/task-session-command-exit-prunes-stale-session-without-worktree ()
  (provide 'consult)
  (require 'my-task-session)
  (let (pruned)
    (cl-letf (((symbol-function 'my/task-resolve-id)
               (lambda (_task)
                 "20260324T082727"))
              ((symbol-function 'my/task-file)
               (lambda (_task-id)
                 "/tmp/task.md"))
              ((symbol-function 'my/task-worktree-repairing)
               (lambda (_task-id)
                 nil))
              ((symbol-function 'denote-retrieve-filename-title)
               (lambda (_file)
                 "Task"))
              ((symbol-function 'my/task-session-prune-stale)
               (lambda (task-id reason)
                 (setq pruned (list task-id reason)))))
      (should-error (my/task-session-command-exit "20260324T082727")
                    :type 'user-error)
      (should (equal pruned
                     '("20260324T082727" missing-worktree))))))

(ert-deftest my/task-session-reset-wip-mixed-resets-recognized-wip-commit ()
  (provide 'consult)
  (require 'my-task-session)
  (let (git-calls)
    (cl-letf (((symbol-function 'my/task-session-wip-commit-p)
               (lambda (task-id _worktree-path)
                 (should (equal task-id "20260324T082727"))
                 t))
              ((symbol-function 'my/git-run-in-dir)
               (lambda (dir &rest args)
                 (push (cons dir args) git-calls)
                 (pcase args
                   (`("rev-parse" "--verify" "HEAD^")
                    '(0 . "parent"))
                   (`("reset" "--mixed" "HEAD^")
                    '(0 . ""))
                   (_
                    (ert-fail (format "unexpected git args: %S" args)))))))
      (should (my/task-session-reset-wip "20260324T082727" "/tmp/worktree/"))
      (should (equal (nreverse git-calls)
                     '(("/tmp/worktree/" "rev-parse" "--verify" "HEAD^")
                       ("/tmp/worktree/" "reset" "--mixed" "HEAD^")))))))

(ert-deftest my/task-session-checkpoint-wip-skips-clean-worktree ()
  (provide 'consult)
  (require 'my-task-session)
  (cl-letf (((symbol-function 'my/worktree-clean-p)
             (lambda (_worktree-path)
               t))
            ((symbol-function 'my/git-run-in-dir)
             (lambda (&rest _args)
               (ert-fail "clean checkpoint should not run git commands"))))
    (should-not (my/task-session--checkpoint-wip "20260324T082727" "/tmp/worktree/"))))

(ert-deftest my/task-session-checkpoint-wip-commits-dirty-worktree ()
  (provide 'consult)
  (require 'my-task-session)
  (let (git-calls)
    (cl-letf (((symbol-function 'my/worktree-clean-p)
               (lambda (_worktree-path)
                 nil))
              ((symbol-function 'my/git-in-merge-or-rebase-p)
               (lambda (_worktree-path)
                 nil))
              ((symbol-function 'my/git-run-in-dir)
               (lambda (dir &rest args)
                 (push (cons dir args) git-calls)
                 (pcase args
                   (`("add" "-A")
                    '(0 . ""))
                   (`("commit" "-m" ,subject)
                    (should (equal subject
                                   "WIP [20260324T082727] checkpoint before exit"))
                    '(0 . "[jamesl-20260324T082727 abc123]"))
                   (_
                    (ert-fail (format "unexpected git args: %S" args)))))))
      (should (equal (my/task-session--checkpoint-wip "20260324T082727" "/tmp/worktree/")
                     "WIP [20260324T082727] checkpoint before exit"))
      (should (equal (nreverse git-calls)
                     '(("/tmp/worktree/" "add" "-A")
                       ("/tmp/worktree/" "commit" "-m"
                        "WIP [20260324T082727] checkpoint before exit")))))))

(ert-deftest my/task-session-release-delegates-to-hephaestus ()
  (provide 'consult)
  (require 'my-task-session)
  (let (calls)
    (cl-letf (((symbol-function 'my/hephaestus-release)
               (lambda (worktree)
                 (push (list 'hephaestus-release worktree) calls)
                 t))
              ((symbol-function 'my/task-session-clear-worktree-state)
               (lambda (task-id)
                 (push (list 'clear-worktree task-id) calls)))
              ((symbol-function 'my/task-session-state-remove)
               (lambda (task-id)
                 (push (list 'state-remove task-id) calls))))
      (my/task-session-release "20260324T082727" "/tmp/worktree/")
      (should (equal (nreverse calls)
                     '((hephaestus-release "/tmp/worktree/")
                       (clear-worktree "20260324T082727")
                       (state-remove "20260324T082727")))))))

(ert-deftest my/task-session-release-surfaces-hephaestus-errors ()
  (provide 'consult)
  (require 'my-task-session)
  (let (cleared removed)
    (cl-letf (((symbol-function 'my/hephaestus-release)
               (lambda (&rest _args)
                 (error "refusing to release dirty worktree: /tmp/worktree/")))
              ((symbol-function 'my/task-session-clear-worktree-state)
               (lambda (&rest _args)
                 (setq cleared t)))
              ((symbol-function 'my/task-session-state-remove)
               (lambda (&rest _args)
                 (setq removed t))))
      (should-error (my/task-session-release "20260324T082727" "/tmp/worktree/")
                    :type 'error)
      (should-not cleared)
      (should-not removed))))

(ert-deftest my/task-session-command-exit-clears-live-session-before-release ()
  (provide 'consult)
  (require 'my-task-session)
  (let (calls last-message)
    (cl-letf (((symbol-function 'my/task-resolve-id)
               (lambda (_task)
                 "20260324T082727"))
              ((symbol-function 'my/task-file)
               (lambda (_task-id)
                 "/tmp/task.md"))
              ((symbol-function 'my/task-worktree-repairing)
               (lambda (_task-id)
                 "/tmp/worktree/"))
              ((symbol-function 'my/task-title)
               (lambda (_file)
                 "Task"))
              ((symbol-function 'my/task-session--checkpoint-wip)
               (lambda (task-id worktree)
                 (push (list 'checkpoint task-id worktree) calls)
                 nil))
              ((symbol-function 'my/task-session-clear-buffer)
               (lambda (task-id)
                 (push (list 'clear-buffer task-id) calls)))
              ((symbol-function 'my/task-session-release)
               (lambda (task-id worktree)
                 (push (list 'release task-id worktree) calls)))
              ((symbol-function 'message)
               (lambda (format-string &rest args)
                 (setq last-message (apply #'format format-string args)))))
      (my/task-session-command-exit "20260324T082727")
      (should (equal (nreverse calls)
                     '((checkpoint "20260324T082727" "/tmp/worktree/")
                       (clear-buffer "20260324T082727")
                       (release "20260324T082727" "/tmp/worktree/"))))
      (should (equal last-message "Task exited: Task")))))

(ert-deftest my/task-session-command-exit-announces-checkpointed-exit ()
  (provide 'consult)
  (require 'my-task-session)
  (let (last-message)
    (cl-letf (((symbol-function 'my/task-resolve-id)
               (lambda (_task)
                 "20260324T082727"))
              ((symbol-function 'my/task-file)
               (lambda (_task-id)
                 "/tmp/task.md"))
              ((symbol-function 'my/task-worktree-repairing)
               (lambda (_task-id)
                 "/tmp/worktree/"))
              ((symbol-function 'my/task-title)
               (lambda (_file)
                 "Task"))
              ((symbol-function 'my/task-session--checkpoint-wip)
               (lambda (_task-id _worktree)
                 "WIP [20260324T082727] checkpoint before exit"))
              ((symbol-function 'my/task-session-clear-buffer)
               (lambda (&rest _args)
                 nil))
              ((symbol-function 'my/task-session-release)
               (lambda (&rest _args)
                 nil))
              ((symbol-function 'message)
               (lambda (format-string &rest args)
                 (setq last-message (apply #'format format-string args)))))
      (my/task-session-command-exit "20260324T082727")
      (should (equal last-message "Task checkpointed and exited: Task")))))

(ert-deftest my/task-session-command-exit-does-not-release-when-checkpoint-fails ()
  (provide 'consult)
  (require 'my-task-session)
  (let (released cleared)
    (cl-letf (((symbol-function 'my/task-resolve-id)
               (lambda (_task)
                 "20260324T082727"))
              ((symbol-function 'my/task-file)
               (lambda (_task-id)
                 "/tmp/task.md"))
              ((symbol-function 'my/task-worktree-repairing)
               (lambda (_task-id)
                 "/tmp/worktree/"))
              ((symbol-function 'my/task-title)
               (lambda (_file)
                 "Task"))
              ((symbol-function 'my/task-session--checkpoint-wip)
               (lambda (&rest _args)
                 (error "checkpoint failed")))
              ((symbol-function 'my/task-session-clear-buffer)
               (lambda (&rest _args)
                 (setq cleared t)))
              ((symbol-function 'my/task-session-release)
               (lambda (&rest _args)
                 (setq released t))))
      (should-error (my/task-session-command-exit "20260324T082727"))
      (should-not cleared)
      (should-not released))))

(ert-deftest my/task-session-create-starts-fresh-session-with-task-id-env ()
  (provide 'consult)
  (require 'my-task-session)
  (let (captured-task-env captured-bootstrap-context)
    (cl-letf (((symbol-function 'my/task-resolve-id)
               (lambda (_task)
                 "20260324T082727"))
              ((symbol-function 'my/task-file)
               (lambda (_task-id)
                 "/tmp/task.md"))
              ((symbol-function 'my/task-worktree-repairing)
               (lambda (_task)
                 "/tmp/worktree"))
              ((symbol-function 'my/task-session-launch-config-normalize)
               (lambda (config)
                 config))
              ((symbol-function 'my/task-session-bootstrap-context)
               (lambda (&rest _args)
                 '(:task-id "20260324T082727"
                   :title "Task"
                   :skill "task-workflow-v3"
                   :task-note-content "## Context\n\nTask body."
                   :agents-files nil)))
              ((symbol-function 'my/agent-bootstrap-prompt)
               (lambda (_backend context)
                 (setq captured-bootstrap-context context)
                 "bootstrap"))
              ((symbol-function 'my/agent-session-start)
               (lambda (&rest _args)
                 (setq captured-task-env
                       (seq-find (lambda (entry)
                                   (string-prefix-p "MY_TASK_ID=" entry))
                                 process-environment))
                 (get-buffer-create "*task-session*")))
              ((symbol-function 'my/task-session-set)
               (lambda (task value)
                 (ert-fail (format "fresh session should not persist via launch path: %s %s"
                                   task value))))
              ((symbol-function 'my/task-session-clear)
               (lambda (&rest _args)
                 (ert-fail "fresh session should not clear stored metadata")))
              ((symbol-function 'my/task-session-state-add)
                (lambda (&rest _args)
                 nil)))
      (unwind-protect
          (progn
            (my/task-session-create "20260324T082727"
                                    '(:backend "pi"
                                      :options (:model "gpt-5.5")))
            (should (equal captured-bootstrap-context
                           '(:task-id "20260324T082727"
                             :title "Task"
                             :skill "task-workflow-v3"
                             :task-note-content "## Context\n\nTask body."
                             :agents-files nil)))
            (should (equal captured-task-env
                           "MY_TASK_ID=20260324T082727")))
        (kill-buffer "*task-session*")))))

(ert-deftest my/task-session-create-persists-compact-pi-session-state-and-worktree ()
  (provide 'consult)
  (provide 'my-theme)
  (provide 'my-agent-pi)
  (require 'my-task-session)
  (let (captured-set captured-start)
    (cl-letf (((symbol-function 'my/task-resolve-id)
               (lambda (_task)
                 "20260405T181044"))
              ((symbol-function 'my/task-file)
               (lambda (_task-id)
                 "/tmp/task.md"))
              ((symbol-function 'my/task-worktree-repairing)
               (lambda (_task)
                 "/Users/jamesl/work/brucenunk/home-config/c"))
              ((symbol-function 'my/task-session-launch-config-normalize)
               (lambda (config)
                 config))
              ((symbol-function 'my/task-session-bootstrap-context)
               (lambda (&rest _args)
                 '(:task-id "20260405T181044"
                   :title "Task"
                   :skill "task-workflow-v3"
                   :task-note-content "## Context\n\nTask body."
                   :agents-files nil)))
              ((symbol-function 'my/agent-bootstrap-prompt)
               (lambda (&rest _args)
                 "bootstrap"))
              ((symbol-function 'my/agent-pi-session-file)
               (lambda (task-id dir)
                 (should (equal task-id "20260405T181044"))
                 (should (equal dir "/Users/jamesl/work/brucenunk/home-config/c"))
                 "/tmp/pi-session.jsonl"))
              ((symbol-function 'my/agent-session-start)
               (lambda (&rest args)
                 (setq captured-start args)
                 (get-buffer-create "*task-session*")))
              ((symbol-function 'my/agent-pi-session-timestamp)
               (lambda (session-file)
                 (should (equal session-file "/tmp/pi-session.jsonl"))
                 "20260422T031929929Z"))
              ((symbol-function 'my/task-note-session-persist-state)
               (lambda (task backend session-id worktree)
                 (setq captured-set (list task backend session-id worktree))))
              ((symbol-function 'my/task-session-state-add)
               (lambda (&rest _args)
                 nil)))
      (unwind-protect
          (progn
            (my/task-session-create "20260405T181044"
                                    '(:backend "pi"
                                      :options (:model "gemma4:26b-mlx" :thinking "medium")))
            (should (equal (plist-get (nthcdr 3 captured-start) :task-id)
                           "20260405T181044"))
            (should (equal (plist-get (nthcdr 3 captured-start) :session-id)
                           "/tmp/pi-session.jsonl"))
            (should (equal (plist-get (nthcdr 3 captured-start) :session-name)
                           "Task"))
            (should (equal captured-set
                           '("20260405T181044" "pi" "20260422T031929929Z" "c"))))
        (when-let ((buffer (get-buffer "*task-session*")))
          (kill-buffer buffer))))))

(ert-deftest my/task-session-stored-resume-state-rejects-bare-pi-marker ()
  (provide 'consult)
  (require 'my-task-session)
  (cl-letf (((symbol-function 'my/task-note-session-get)
             (lambda (_task-id)
               "pi")))
    (should-error (my/task-session--stored-resume-state "20260405T181044")
                  :type 'user-error)))

(ert-deftest my/task-session-stored-resume-state-ignores-removed-codex-backend ()
  (provide 'consult)
  (require 'my-task-session)
  (cl-letf (((symbol-function 'my/task-note-session-get)
             (lambda (_task-id)
               "codex:uuid-123")))
    (should-not (my/task-session--stored-resume-state "20260405T181044"))))

(ert-deftest my/task-session-stored-resume-state-still-errors-on-other-unknown-backends ()
  (provide 'consult)
  (require 'my-task-session)
  (cl-letf (((symbol-function 'my/task-note-session-get)
             (lambda (_task-id)
               "legacy:uuid-123")))
    (should-error (my/task-session--stored-resume-state "20260405T181044")
                  :type 'user-error)))
(ert-deftest my/task-session-worktree-root-from-path-finds-direct-child-worktree ()
  (provide 'consult)
  (require 'my-task-session)
  (should (equal (my/task-session-worktree-root-from-path
                  "/Users/jamesl/work/brucenunk/home-config/scratch/src/file.el")
                 "/Users/jamesl/work/brucenunk/home-config/scratch/")))

(ert-deftest my/task-session-resolve-pi-resume-state-reconstructs-path-from-timestamp-and-worktree ()
  (provide 'consult)
  (provide 'my-theme)
  (provide 'my-agent-pi)
  (require 'my-task-session)
  (let ((worktree "/Users/jamesl/work/brucenunk/home-config/scratch")
        persist-call)
    (cl-letf (((symbol-function 'my/agent-pi-session-resolve)
               (lambda (task-id dir session-id)
                 (should (equal task-id "20260405T181044"))
                 (should (equal dir worktree))
                 (should (equal session-id "20260422T031929929Z"))
                 '(:id "/tmp/pi/sessions/--worktree--/2026-04-22T03-19-29-929Z_20260405T181044.jsonl")))
              ((symbol-function 'my/agent-pi-session-timestamp)
               (lambda (session-file)
                 (should (equal session-file
                                "/tmp/pi/sessions/--worktree--/2026-04-22T03-19-29-929Z_20260405T181044.jsonl"))
                 "20260422T031929929Z"))
              ((symbol-function 'my/task-note-worktree-get)
               (lambda (&rest _args)
                 nil))
              ((symbol-function 'my/task-note-session-persist-state)
               (lambda (&rest args)
                 (setq persist-call args))))
      (should (equal (my/task-session--resolve-pi-resume-state
                      "20260405T181044"
                      worktree
                      '(:backend "pi" :id "20260422T031929929Z"))
                     '(:backend "pi" :id "/tmp/pi/sessions/--worktree--/2026-04-22T03-19-29-929Z_20260405T181044.jsonl")))
      (should (equal persist-call
                     '("20260405T181044" "pi" "20260422T031929929Z" "scratch"))))))

(ert-deftest my/task-session-resolve-pi-resume-state-avoids-rewriting-unchanged-note ()
  (provide 'consult)
  (provide 'my-theme)
  (provide 'my-agent-pi)
  (require 'my-task-session)
  (cl-letf (((symbol-function 'my/agent-pi-session-resolve)
             (lambda (_task-id _dir session-id)
               (should (equal session-id "20260422T031929929Z"))
               '(:id "/tmp/pi/sessions/--scratch--/2026-04-22T03-19-29-929Z_20260405T181044.jsonl")))
            ((symbol-function 'my/agent-pi-session-timestamp)
             (lambda (session-file)
               (should (equal session-file
                              "/tmp/pi/sessions/--scratch--/2026-04-22T03-19-29-929Z_20260405T181044.jsonl"))
               "20260422T031929929Z"))
            ((symbol-function 'my/task-note-worktree-get)
             (lambda (&rest _args)
               "scratch"))
            ((symbol-function 'my/task-note-session-persist-state)
             (lambda (&rest _args)
               (ert-fail "unchanged compact Pi resume should not rewrite the task note"))))
    (should (equal (my/task-session--resolve-pi-resume-state
                    "20260405T181044"
                    "/Users/jamesl/work/brucenunk/home-config/scratch"
                    '(:backend "pi" :id "20260422T031929929Z"))
                   '(:backend "pi" :id "/tmp/pi/sessions/--scratch--/2026-04-22T03-19-29-929Z_20260405T181044.jsonl")))))

(ert-deftest my/task-session-create-resumes-stored-session-with-backend-dispatch ()
  (provide 'consult)
  (require 'my-task-session)
  (let (resume-call captured-task-env)
    (cl-letf (((symbol-function 'my/task-resolve-id)
               (lambda (_task)
                 "20260324T082727"))
              ((symbol-function 'my/task-file)
               (lambda (_task-id)
                 "/tmp/task.md"))
              ((symbol-function 'my/task-worktree-repairing)
               (lambda (_task)
                 "/tmp/worktree"))
              ((symbol-function 'my/task-session-launch-config-normalize)
               (lambda (config)
                 config))
              ((symbol-function 'my/task-session-bootstrap-context)
               (lambda (&rest _args)
                 '(:task-id "20260324T082727"
                   :title "Task"
                   :skill "task-workflow-v3"
                   :task-note-content "## Context\n\nTask body."
                   :agents-files nil)))
              ((symbol-function 'my/agent-bootstrap-prompt)
               (lambda (&rest _args)
                 "bootstrap"))
              ((symbol-function 'my/agent-session-start)
               (lambda (&rest _args)
                 (ert-fail "stored metadata should use resume dispatch")))
              ((symbol-function 'my/agent-session-resume-start)
               (lambda (&rest args)
                 (setq resume-call args)
                 (setq captured-task-env
                       (seq-find (lambda (entry)
                                   (string-prefix-p "MY_TASK_ID=" entry))
                                 process-environment))
                 (get-buffer-create "*task-session*")))
              ((symbol-function 'my/task-session-set)
               (lambda (&rest _args)
                 (ert-fail "resume path should not overwrite session metadata")))
              ((symbol-function 'my/task-session-clear)
               (lambda (&rest _args)
                 (ert-fail "resume path should not clear session metadata")))
              ((symbol-function 'my/task-session-state-add)
               (lambda (&rest _args)
                 nil)))
      (unwind-protect
          (progn
            (my/task-session-create "20260324T082727"
                                    '(:backend "pi"
                                      :options (:model "gpt-5.5"))
                                    :resume-state '(:backend "pi" :id "20260422T031929929Z"))
            (should (equal (seq-take resume-call 4)
                           '("pi"
                             "/Users/jamesl/.pi/agent/sessions/--tmp-worktree--/2026-04-22T03-19-29-929Z_20260324T082727.jsonl"
                             "agent-task-20260324T082727"
                             "/tmp/worktree")))
            (should (equal (plist-get (nthcdr 4 resume-call) :options)
                           '(:model "gpt-5.5")))
            (should (equal (plist-get (nthcdr 4 resume-call) :bootstrap-prompt)
                           "bootstrap"))
            (should (equal captured-task-env
                           "MY_TASK_ID=20260324T082727")))
        (kill-buffer "*task-session*")))))

(ert-deftest my/task-session-create-resumes-missing-explicit-pi-session-with-bootstrap-prompt ()
  (provide 'consult)
  (require 'my-task-session)
  (let (resume-call)
    (cl-letf (((symbol-function 'my/task-resolve-id)
               (lambda (_task)
                 "20260324T082727"))
              ((symbol-function 'my/task-file)
               (lambda (_task-id)
                 "/tmp/task.md"))
              ((symbol-function 'my/task-worktree-repairing)
               (lambda (_task)
                 "/tmp/worktree"))
              ((symbol-function 'my/task-session-launch-config-normalize)
               (lambda (config)
                 config))
              ((symbol-function 'my/task-session-bootstrap-context)
               (lambda (&rest _args)
                 '(:task-id "20260324T082727" :title "Task" :task-note-content "body")))
              ((symbol-function 'my/agent-bootstrap-prompt)
               (lambda (&rest _args)
                 "bootstrap"))
              ((symbol-function 'my/task-session--resolve-pi-resume-state)
               (lambda (&rest _args)
                 '(:backend "pi" :id "/tmp/missing-session.jsonl")))
              ((symbol-function 'file-exists-p)
               (lambda (path)
                 (not (equal path "/tmp/missing-session.jsonl"))))
              ((symbol-function 'my/agent-session-start)
               (lambda (&rest _args)
                 (ert-fail "explicit Pi metadata should use resume dispatch")))
              ((symbol-function 'my/agent-session-resume-start)
               (lambda (&rest args)
                 (setq resume-call args)
                 (get-buffer-create "*task-session*")))
              ((symbol-function 'my/task-session-state-add)
               (lambda (&rest _args)
                 nil)))
      (unwind-protect
          (progn
            (my/task-session-create "20260324T082727"
                                    '(:backend "pi"
                                      :options (:model "gpt-5.5"))
                                    :resume-state '(:backend "pi" :id "20260422T031929929Z"))
            (should (equal (seq-take resume-call 4)
                           '("pi" "/tmp/missing-session.jsonl" "agent-task-20260324T082727" "/tmp/worktree")))
            (should (equal (plist-get (nthcdr 4 resume-call) :bootstrap-prompt)
                           "bootstrap"))
            (should (equal (plist-get (nthcdr 4 resume-call) :session-name)
                           "Task")))
        (when-let ((buffer (get-buffer "*task-session*")))
          (kill-buffer buffer))))))

(ert-deftest my/task-session-pickup-resume-launch-config-keeps-advanced-options ()
  (provide 'consult)
  (require 'my-task-session)
  (let (prompt-call)
    (cl-letf (((symbol-function 'my/agent-backend-options-default)
               (lambda (backend)
                 (should (equal backend "pi"))
                 '(:model "gpt-5.5" :thinking "medium")))
              ((symbol-function 'my/agent-backend-options-prompt)
               (lambda (backend initial-options advanced-p)
                 (setq prompt-call (list backend initial-options advanced-p))
                 '(:model "gpt-5.5" :thinking "high"))))
      (should (equal (my/task-session--pickup-resolve-launch-config
                      t
                      nil
                      t
                      '(:backend "pi" :id "20260422T031929929Z"))
                     '(:backend "pi"
                       :options (:model "gpt-5.5" :thinking "high"))))
      (should (equal prompt-call
                     '("pi" (:model "gpt-5.5" :thinking "medium") t))))))

(ert-deftest my/task-session-pickup-launch-config-advanced-skips-backend-prompt-for-single-backend ()
  (provide 'consult)
  (require 'my-task-session)
  (let (options-call)
    (cl-letf (((symbol-function 'my/agent-single-backend)
               (lambda ()
                 "pi"))
              ((symbol-function 'my/agent-backend-prompt)
               (lambda (&rest _args)
                 (ert-fail "single backend should not prompt for backend selection")))
              ((symbol-function 'my/agent-default-backend-resolve)
               (lambda ()
                 (ert-fail "single backend should not resolve prompt default")))
              ((symbol-function 'my/agent-backend-options-default)
               (lambda (backend)
                 (should (equal backend "pi"))
                 '(:model "gemma4:26b-mlx" :thinking "medium")))
              ((symbol-function 'my/agent-backend-options-prompt)
               (lambda (backend initial-options advanced-p)
                 (setq options-call (list backend initial-options advanced-p))
                 '(:model "gemma4:26b-mlx" :thinking "high"))))
      (should (equal (my/task-session-pickup-launch-config t)
                     '(:backend "pi"
                       :options (:model "gemma4:26b-mlx" :thinking "high"))))
      (should (equal options-call
                     '("pi" (:model "gemma4:26b-mlx" :thinking "medium") t))))))

(ert-deftest my/task-session-pickup-launch-config-advanced-prompts-backend-and-options ()
  (provide 'consult)
  (require 'my-task-session)
  (let (calls)
    (cl-letf (((symbol-function 'my/agent-single-backend)
               (lambda ()
                 nil))
              ((symbol-function 'my/agent-default-backend-resolve)
               (lambda ()
                 (push 'backend-default calls)
                 "pi"))
              ((symbol-function 'my/agent-backend-prompt)
               (lambda (_initial-backend)
                 (push 'backend-prompt calls)
                 "pi"))
              ((symbol-function 'my/agent-backend-options-default)
               (lambda (_backend)
                 (push 'options-default calls)
                 '(:model "gpt-5.5" :thinking "medium")))
              ((symbol-function 'my/agent-backend-options-prompt)
               (lambda (_backend _initial-options _advanced-p)
                 (push 'options-prompt calls)
                 '(:model "gpt-5.5" :thinking "high"))))
      (should (equal (my/task-session-pickup-launch-config t)
                     '(:backend "pi"
                       :options (:model "gpt-5.5" :thinking "high"))))
      (should (equal (nreverse calls)
                     '(backend-default
                       backend-prompt
                       options-default
                       options-prompt))))))

(ert-deftest my/task-session-restore-view-reuses-selected-window ()
  (require 'my-task-session)
  (save-window-excursion
    (let ((session-buffer (get-buffer-create " *my-task-session-restore*"))
          resized)
      (unwind-protect
          (progn
            (delete-other-windows)
            (switch-to-buffer (get-buffer-create " *my-task-origin*"))
            (split-window-right)
            (other-window 1)
            (switch-to-buffer (get-buffer-create " *my-task-side*"))
            (other-window -1)
            (cl-letf (((symbol-function 'my/task-resolve-id)
                       (lambda (_task)
                         "20260324T082727"))
                      ((symbol-function 'my/task-note-file)
                       (lambda (_task-id)
                         "/tmp/task.md"))
                      ((symbol-function 'my/task-worktree-repairing)
                       (lambda (_file)
                         "/tmp/worktree/"))
                      ((symbol-function 'my/task-session-ensure-live)
                       (lambda (_task-id)
                         session-buffer))
                      ((symbol-function 'my/task-session-kill-orphaned-buffers)
                       (lambda () nil))
                      ((symbol-function 'my/agent-session-resize-to-window)
                       (lambda (buffer window)
                         (setq resized (list buffer window))))
                      ((symbol-function 'switch-to-buffer)
                       (lambda (&rest _args)
                         (ert-fail "restore should target the selected window directly"))))
              (my/task-session-restore-view "20260324T082727")
              (should (= (length (window-list)) 2))
              (should (eq (window-buffer (selected-window)) session-buffer))
              (should (equal resized (list session-buffer (selected-window))))
              (should (eq (window-buffer (next-window))
                          (get-buffer " *my-task-side*")))))
        (kill-buffer session-buffer)))))

(ert-deftest my/task-session-kill-orphaned-buffers-skips-buffer-local-query ()
  (provide 'consult)
  (require 'my-task-session)
  (let ((buffer (generate-new-buffer "agent-task-20260727T095133")))
    (unwind-protect
        (progn
          (with-current-buffer buffer
            (setq-local my/task-session-task-id "20260727T095133")
            (setq-local kill-buffer-query-functions
                        (list (lambda ()
                                (ert-fail "Orphan cleanup prompted before killing")))))
          (cl-letf (((symbol-function 'my/task-session-state-active-p)
                     (lambda (_task-id) nil)))
            (my/task-session-kill-orphaned-buffers))
          (should-not (buffer-live-p buffer)))
      (when (buffer-live-p buffer)
        (with-current-buffer buffer
          (let ((kill-buffer-query-functions nil))
            (kill-buffer)))))))

(ert-deftest my/task-session-pickup-start-async-live-session-uses-snapshot-worktree ()
  (provide 'consult)
  (require 'my-task-session)
  (let (captured)
    (cl-letf (((symbol-function 'my/task-session--pickup-preflight-check)
               (lambda (_task-id)
                 nil))
              ((symbol-function 'my/task-session-ensure-live)
               (lambda (_task-id)
                 'live-session))
              ((symbol-function 'my/task-session-sync-entry)
               (lambda (_task-id _live-session)
                 nil))
              ((symbol-function 'my/task-worktree)
               (lambda (task-id)
                 (should (equal task-id "20260324T082727"))
                 "/tmp/worktree/"))
              ((symbol-function 'my/task-worktree-repairing)
               (lambda (&rest _)
                 (ert-fail "Live-session pickup result should not repair worktree state")))
              ((symbol-function 'my/task-session-restore-view)
               (lambda (&rest _)
                 (ert-fail "Restore should stay disabled for this test"))))
      (my/task-session-pickup-start-async
       "20260324T082727"
       :restore-session nil
       :on-success (lambda (result)
                     (setq captured result)))
      (should (equal captured
                     '(:task-id "20260324T082727"
                       :worktree "/tmp/worktree/"
                       :outcome live))))))

(ert-deftest my/task-session-pickup-start-async-resumes-stored-session-metadata ()
  (provide 'consult)
  (require 'my-task-session)
  (let (captured-create)
    (cl-letf (((symbol-function 'my/task-session--pickup-preflight-check)
               (lambda (_task-id)
                 nil))
              ((symbol-function 'my/task-session-ensure-live)
               (lambda (_task-id)
                 nil))
              ((symbol-function 'my/task-session-get)
               (lambda (_task-id)
                 "pi:20260422T031929929Z"))
              ((symbol-function 'my/agent-backend-options-default)
               (lambda (backend)
                 (should (equal backend "pi"))
                 '(:model "gpt-5.5")))
              ((symbol-function 'my/task-session-prepare-work-async)
               (lambda (_task-id &rest args)
                 (funcall (plist-get args :on-success)
                          '(:task-id "20260324T082727"
                            :worktree "/tmp/worktree"))))
              ((symbol-function 'my/task-session-create)
               (lambda (_task launch-config &rest args)
                 (setq captured-create (list launch-config
                                             (plist-get args :resume-state))))))
      (my/task-session-pickup-start-async
       "20260324T082727"
       :restore-session nil
       :on-success (lambda (_result) nil)
       :on-error (lambda (err-msg)
                   (ert-fail err-msg)))
      (should (equal captured-create
                     '((:backend "pi"
                         :options (:model "gpt-5.5"))
                       (:backend "pi" :id "20260422T031929929Z")))))))

(ert-deftest my/task-session-pickup-start-async-errors-on-invalid-stored-session-metadata ()
  (provide 'consult)
  (require 'my-task-session)
  (let (captured-error)
    (cl-letf (((symbol-function 'my/task-session--pickup-preflight-check)
               (lambda (_task-id)
                 nil))
              ((symbol-function 'my/task-session-ensure-live)
               (lambda (_task-id)
                 nil))
              ((symbol-function 'my/task-session-get)
               (lambda (_task-id)
                 "invalid"))
              ((symbol-function 'my/task-session-prepare-work-async)
               (lambda (&rest _args)
                 (ert-fail "invalid stored metadata should fail before worktree prep"))))
      (my/task-session-pickup-start-async
       "20260324T082727"
       :restore-session nil
       :on-success (lambda (_result)
                     (ert-fail "invalid stored metadata should not succeed"))
       :on-error (lambda (err-msg)
                   (setq captured-error err-msg)))
      (should (string-match-p "Stored session metadata" captured-error)))))

(ert-deftest my/task-session-command-pickup-notifies-when-unusable-worktrees-were-skipped ()
  (provide 'consult)
  (require 'my-task-session)
  (let (captured-message)
    (cl-letf (((symbol-function 'my/task-resolve-id)
               (lambda (_task)
                 "20260324T082727"))
              ((symbol-function 'my/task-session-pickup-start-async)
               (lambda (_task-id &rest args)
                 (funcall (plist-get args :on-success)
                          '(:outcome started
                            :unusable-worktrees ((:path "/tmp/e/" :reason dirty))))))
              ((symbol-function 'message)
               (lambda (format-string &rest args)
                 (setq captured-message (apply #'format format-string args)))))
      (my/task-session-command-pickup "20260324T082727")
      (should (equal captured-message
                     "Skipped unusable worktrees: /tmp/e/")))))

(provide 'my-task-session-tests)
;;; my-task-session-tests.el ends here
