;;; my-task-tests.el --- Tests for core task behavior -*- lexical-binding: t -*-

;;; Commentary:

;; Core task state, notifications, and recovery coverage.

;;; Code:

(require 'my-task-test-support)
(require 'my-task-finish)

(ert-deftest my/task-list-loads-before-task-hook-provider ()
  (my/task-index-test--with-unloaded-ui-modules
    (should (load "my-task-list" nil t))
    (should (boundp 'my/task-state-change-functions))))

(ert-deftest my/task-requires-index-for-direct-snapshot-accessors ()
  (unwind-protect
      (progn
        (unload-feature 'my-task t)
        (unload-feature 'my-task-index t)
        (should (require 'my-task))
        (should (featurep 'my-task-index)))
    (require 'my-task-index)
    (require 'my-task)))

(ert-deftest my/task-state-entries-copies-indexed-state-without-repair ()
  (let ((entry (my/task-index-test--entry
                "20260324T103418"
                :worktree "/tmp/a/"
                :active t))
        repair-called)
    (cl-letf (((symbol-function 'my/task-startup-recover-index-async)
               (lambda (&rest _args)
                 nil))
              ((symbol-function 'my/task--repair-index)
               (lambda ()
                 (setq repair-called t)
                 (ert-fail "UI snapshot read should not run global repair")))
              ((symbol-function 'my/task-index-entries)
               (lambda ()
                 (list entry))))
      (let* ((result (my/task-state-entries))
             (result-entry (car result)))
        (should-not repair-called)
        (should (equal result-entry entry))
        (setf (plist-get result-entry :worktree) "/tmp/changed/")
        (should (equal (plist-get entry :worktree) "/tmp/a/"))))))

(ert-deftest my/task-state-entries-matches-raw-snapshot-shape ()
  (let ((entry (my/task-index-test--entry
                "20260324T103418"
                :worktree "/tmp/a/")))
    (cl-letf (((symbol-function 'my/task-startup-recover-index-async)
               (lambda (&rest _args)
                 nil))
              ((symbol-function 'my/task-index-entries)
               (lambda ()
                 (list entry))))
      (should (equal (my/task-state-entries)
                     (my/task-state-entries-raw))))))

(ert-deftest my/task-state-entries-stays-on-cached-snapshot-without-live-git ()
  (let ((entry (my/task-index-test--entry
                "20260324T103418"
                :worktree "/tmp/a/")))
    (cl-letf (((symbol-function 'my/task-startup-recover-index-async)
               (lambda (&rest _args)
                 nil))
              ((symbol-function 'my/task-index-entries)
               (lambda ()
                 (list entry)))
              ((symbol-function 'my/worktree-list-for-repo)
               (lambda (&rest _args)
                 (ert-fail "task state snapshot should not perform live git scans"))))
      (should (equal (my/task-state-entries)
                     (list entry))))))

(ert-deftest my/task-state-entries-raw-returns-detached-copies ()
  (let ((entry (my/task-index-test--entry
                "20260324T103418"
                :worktree "/tmp/a/")))
    (cl-letf (((symbol-function 'my/task-index-entries)
               (lambda ()
                 (list entry))))
      (let ((result-entry (car (my/task-state-entries-raw))))
        (setf (plist-get result-entry :worktree) "/tmp/changed/")
        (should (equal (plist-get entry :worktree) "/tmp/a/"))))))

(ert-deftest my/task-find-by-worktree-uses-index-without-repair ()
  (let ((task-id "20260324T103418"))
    (cl-letf (((symbol-function 'my/task--repair-index)
               (lambda ()
                 (ert-fail "Indexed worktree lookup should not run global repair")))
              ((symbol-function 'my/task-index-find-by-worktree)
               (lambda (path)
                 (should (equal path "/tmp/a/"))
                 task-id))
              ((symbol-function 'my/task-file)
               (lambda (id)
                 (should (equal id task-id))
                 "/tmp/task.md")))
      (should (equal (my/task-find-by-worktree "/tmp/a/")
                     "/tmp/task.md")))))

(ert-deftest my/task-find-by-worktree-loads-repair-helper-for-branch-fallback ()
  (let ((task-id "20260414T215613")
        (worktree "/Users/jamesl/work/brucenunk/home-config/b/"))
    (cl-letf (((symbol-function 'my/task-index-find-by-worktree)
               (lambda (_path) nil))
              ((symbol-function 'file-directory-p)
               (lambda (path)
                 (equal path worktree)))
              ((symbol-function 'my/git-branch)
               (lambda (path)
                 (should (equal path worktree))
                 "jamesl-20260414T215613"))
              ((symbol-function 'my/task-file)
               (lambda (id)
                 (should (equal id task-id))
                 "/tmp/task.md"))
              ((symbol-function 'my/task-owner-repo)
               (lambda (task)
                 (should (equal task "/tmp/task.md"))
                 '("brucenunk" . "home-config")))
              ((symbol-function 'my/task--feature-worktree-p)
               (lambda (path)
                 (equal path worktree)))
              ((symbol-function 'require)
               (lambda (feature &optional _filename _noerror)
                 (should (eq feature 'my-worktree-repair))
                 'my-worktree-repair))
              ((symbol-function 'my/worktree-repair-branch-task-id)
               (lambda (branch)
                 (should (equal branch "jamesl-20260414T215613"))
                 task-id)))
      (should (equal (my/task-find-by-worktree worktree)
                     "/tmp/task.md")))))

(ert-deftest my/task-find-by-worktree-branch-fallback-rejects-task-from-different-repo ()
  (let ((worktree "/Users/jamesl/work/brucenunk/home-config/b/"))
    (cl-letf (((symbol-function 'my/task-index-find-by-worktree)
               (lambda (_path) nil))
              ((symbol-function 'file-directory-p)
               (lambda (path)
                 (equal path worktree)))
              ((symbol-function 'my/git-branch)
               (lambda (_path)
                 "jamesl-20260414T215613"))
              ((symbol-function 'my/task--feature-worktree-p)
               (lambda (path)
                 (equal path worktree)))
            ((symbol-function 'my/task-file)
             (lambda (_task-id)
               "/tmp/task.md"))
            ((symbol-function 'my/task-owner-repo)
             (lambda (_task)
               '("other" . "repo")))
              ((symbol-function 'my/worktree-repair-branch-task-id)
               (lambda (_branch)
                 "20260414T215613")))
      (should-not (my/task-find-by-worktree worktree)))))

(ert-deftest my/task-find-by-worktree-ignores-default-worktree-paths ()
  (cl-letf (((symbol-function 'my/task-index-find-by-worktree)
             (lambda (_path) nil))
            ((symbol-function 'my/git-branch)
             (lambda (&rest _args)
               (ert-fail "default worktree paths should not fall back to branch lookup"))))
    (should-not (my/task-find-by-worktree
                 "/Users/jamesl/work/brucenunk/home-config/main/"))))

(ert-deftest my/task--feature-worktree-p-accepts-non-single-letter-direct-child-worktrees ()
  (cl-letf (((symbol-function 'my/worktree-list-for-repo)
             (lambda (_owner _repo)
               '((:path "/Users/jamesl/work/brucenunk/home-config/main/")
                 (:path "/Users/jamesl/work/brucenunk/home-config/scratch/")
                 (:path "/Users/jamesl/work/brucenunk/home-config/scratch/nested/"))))
            ((symbol-function 'my/worktree-default-for-repo)
             (lambda (_owner _repo)
               "/Users/jamesl/work/brucenunk/home-config/main/")))
    (should (my/task--feature-worktree-p
             "/Users/jamesl/work/brucenunk/home-config/scratch/"))
    (should-not (my/task--feature-worktree-p
                 "/Users/jamesl/work/brucenunk/home-config/scratch/nested/"))
    (should-not (my/task--feature-worktree-p
                 "/Users/jamesl/work/brucenunk/home-config/main/"))))

(ert-deftest my/task-find-by-worktree-ignores-missing-feature-worktree-paths ()
  (cl-letf (((symbol-function 'my/task-index-find-by-worktree)
             (lambda (_path) nil))
            ((symbol-function 'file-directory-p)
             (lambda (_path)
               nil))
            ((symbol-function 'my/git-branch)
             (lambda (&rest _args)
               (ert-fail "missing worktree paths should not run git branch lookup"))))
    (should-not (my/task-find-by-worktree "/tmp/missing-feature-slot/"))))

(ert-deftest my/task-file-falls-back-across-shared-task-root ()
  (let* ((temp-root (make-temp-file "my-task-shared-root" t))
         (tasks-root (expand-file-name "tasks/" temp-root))
         (epic-dir (expand-file-name "session-bugs/" tasks-root))
         (task-id "20260324T103418")
         (task-file (expand-file-name
                     (format "%s==todo--shared-root.md" task-id)
                     epic-dir))
         (my/task--file-cache (make-hash-table :test 'equal)))
    (make-directory epic-dir t)
    (unwind-protect
        (progn
          (with-temp-file task-file
            (insert "---\n---\n"))
          (cl-letf (((symbol-function 'my/task--task-directories)
                     (lambda ()
                       (list tasks-root)))
                    ((symbol-function 'denote-get-path-by-id) (lambda (_id) nil))
                    ((symbol-function 'denote-retrieve-filename-signature)
                     (lambda (file)
                       (should (equal file task-file))
                       "todo")))
            (let ((denote-directory tasks-root))
              (should (equal (my/task-file task-id) task-file))
              (should (equal (my/task-status task-id) "todo")))))
      (delete-directory temp-root t))))

(ert-deftest my/task-file-caches-cross-owner-fallback-hit ()
  (let* ((temp-file (make-temp-file "my-task-cache"))
         (task-id "20260324T103418")
         (my/task--file-cache (make-hash-table :test 'equal))
         (search-calls 0))
    (unwind-protect
        (cl-letf (((symbol-function 'denote-get-path-by-id)
                   (lambda (_task-id)
                     nil))
                  ((symbol-function 'my/task--find-file-in-task-directories)
                   (lambda (id)
                     (should (equal id task-id))
                     (setq search-calls (1+ search-calls))
                     temp-file)))
          (should (equal (my/task-file task-id) temp-file))
          (should (equal (my/task-file task-id) temp-file))
          (should (= search-calls 1)))
      (delete-file temp-file t))))

(ert-deftest my/task-worktree-uses-indexed-snapshot-without-repair ()
  (my/task-index-test--with-isolated-index
    (let ((task-id "20260324T103418"))
      (puthash task-id
               (my/task-index-test--entry task-id :worktree "/tmp/a/" :active t)
               my/task-index)
      (cl-letf (((symbol-function 'my/task-index-worktree)
                 (lambda (id)
                   (should (equal id task-id))
                   "/tmp/a/")))
        (should (equal (my/task-worktree task-id) "/tmp/a/"))))))

(ert-deftest my/task-worktree-repairing-prefers-indexed-snapshot-before-live-lookup ()
  (cl-letf (((symbol-function 'my/task-index-worktree)
             (lambda (task-id)
               (should (equal task-id "20260324T103418"))
               "/tmp/indexed/"))
            ((symbol-function 'file-directory-p)
             (lambda (path)
               (equal path "/tmp/indexed/")))
            ((symbol-function 'my/git-branch)
             (lambda (path)
               (should (equal path "/tmp/indexed/"))
               "jamesl-20260324T103418"))
            ((symbol-function 'my/worktree-attached-for-branch)
             (lambda (&rest _args)
               (ert-fail "indexed worktree should avoid live lookup"))))
    (should (equal (my/task-worktree-repairing "20260324T103418")
                   "/tmp/indexed/"))))

(ert-deftest my/task-worktree-repairing-ignores-stale-indexed-branch-and-falls-back-live ()
  (cl-letf (((symbol-function 'my/task-index-worktree)
             (lambda (_task-id)
               "/tmp/reused/"))
            ((symbol-function 'file-directory-p)
             (lambda (path)
               (member path '("/tmp/reused/" "/tmp/live/"))))
            ((symbol-function 'my/git-branch)
             (lambda (path)
               (when (equal path "/tmp/reused/")
                 "jamesl-20260324T999999")))
            ((symbol-function 'my/task-file)
             (lambda (_task-id)
               "/tmp/task.md"))
            ((symbol-function 'my/task-note-owner-repo)
             (lambda (_task-file)
               '("brucenunk" . "home-config")))
            ((symbol-function 'my/task--feature-worktree-p)
             (lambda (path)
               (equal path "/tmp/live/")))
            ((symbol-function 'my/worktree-attached-for-branch)
             (lambda (_owner _repo _branch)
               "/tmp/live/")))
    (should (equal (my/task-worktree-repairing "20260414T215613")
                   "/tmp/live/"))))

(ert-deftest my/task-worktree-ignores-default-worktree-branch-match ()
  (cl-letf (((symbol-function 'my/task-file)
             (lambda (_task-id)
               "/tmp/task.md"))
            ((symbol-function 'my/task-note-owner-repo)
             (lambda (_task-file)
               '("brucenunk" . "home-config")))
            ((symbol-function 'my/worktree-attached-for-branch)
             (lambda (_owner _repo _branch)
               "/Users/jamesl/work/brucenunk/home-config/main/")))
    (should-not (my/task-worktree "20260414T215613"))))

(ert-deftest my/task-worktree-repairing-ignores-missing-indexed-path-and-falls-back-live ()
  (cl-letf (((symbol-function 'my/task-index-worktree)
             (lambda (_task-id)
               "/tmp/missing/"))
            ((symbol-function 'file-directory-p)
             (lambda (path)
               (equal path "/tmp/live/")))
            ((symbol-function 'my/task-file)
             (lambda (_task-id)
               "/tmp/task.md"))
            ((symbol-function 'my/task-note-owner-repo)
             (lambda (_task-file)
               '("brucenunk" . "home-config")))
            ((symbol-function 'my/task--feature-worktree-p)
             (lambda (path)
               (equal path "/tmp/live/")))
            ((symbol-function 'my/worktree-attached-for-branch)
             (lambda (_owner _repo _branch)
               "/tmp/live/")))
    (should (equal (my/task-worktree-repairing "20260414T215613")
                   "/tmp/live/"))))

(ert-deftest my/task-owner-from-path-reads-worktree-paths-but-not-task-root ()
  (should (equal (my/task-owner-from-path "/Users/jamesl/work/brucenunk/home-config/g/")
                 "brucenunk"))
  (should-not (my/task-owner-from-path
               "/Users/jamesl/work/tasks/task-system-overhaul/task.md"))
  (should-not (my/task-owner-from-path "/tmp/not-a-worktree")))

(ert-deftest my/worktree-default-for-path-parses-direct-child-worktree-under-work-root ()
  (cl-letf (((symbol-function 'my/worktree-default-for-repo)
             (lambda (owner repo)
               (list owner repo))))
    (should (equal (my/worktree-default-for-path
                    "/Users/jamesl/work/brucenunk/home-config/scratch/")
                   '("brucenunk" "home-config")))))

(ert-deftest my/task-repo-snapshot-derives-repo-from-indexed-worktree ()
  (cl-letf (((symbol-function 'my/task-index-get)
             (lambda (task-id)
               (should (equal task-id "20260324T103418"))
               (list :task-id task-id
                     :worktree "/Users/jamesl/work/brucenunk/home-config/g/")))
            ((symbol-function 'my/task-repo)
             (lambda (&rest _args)
               (ert-fail "indexed worktree repo should avoid task lookup"))))
    (should (equal (my/task-repo-snapshot "20260324T103418")
                   "home-config"))))

(ert-deftest my/task-owner-and-repo-parse-combined-front-matter-slug ()
  (let ((task-file "/tmp/20260324T103418==todo--shared-root.md"))
    (cl-letf (((symbol-function 'my/task--front-matter-get-from-file)
               (lambda (_file field)
                 (pcase field
                   ("repo" "example/project")))))
      (should (equal (my/task-owner task-file) "example"))
      (should (equal (my/task-repo task-file) "project")))))

(ert-deftest my/task-owner-repo-snapshot-prefers-indexed-worktree-before-task-lookup ()
  (cl-letf (((symbol-function 'my/task-index-get)
             (lambda (task-id)
               (should (equal task-id "20260324T103418"))
               (list :task-id task-id
                     :worktree "/Users/jamesl/work/brucenunk/home-config/g/")))
            ((symbol-function 'my/task-owner-repo)
             (lambda (&rest _args)
               (ert-fail "indexed worktree pair should avoid task lookup"))))
    (should (equal (my/task-owner-repo-snapshot "20260324T103418")
                   '("brucenunk" . "home-config")))))

(ert-deftest my/task-owner-snapshot-derives-owner-from-indexed-worktree ()
  (cl-letf (((symbol-function 'my/task-index-get)
             (lambda (task-id)
               (should (equal task-id "20260324T103418"))
               (list :task-id task-id
                     :worktree "/Users/jamesl/work/brucenunk/home-config/g/")))
            ((symbol-function 'my/task-owner-repo)
             (lambda (&rest _args)
               (ert-fail "indexed worktree owner should avoid task lookup"))))
    (should (equal (my/task-owner-snapshot "20260324T103418")
                   "brucenunk"))))

(ert-deftest my/task-owner-repo-snapshot-falls-back-to-task-lookup ()
  (cl-letf (((symbol-function 'my/task-index-get)
             (lambda (task-id)
               (should (equal task-id "20260324T103418"))
               nil))
            ((symbol-function 'my/task-owner-repo)
             (lambda (&rest _args)
               '("brucenunk" . "home-config"))))
    (should (equal (my/task-owner-repo-snapshot "20260324T103418")
                   '("brucenunk" . "home-config")))))

(ert-deftest my/task-session-format-and-parse-roundtrip ()
  (should (equal (my/task-session-format "pi" "20260422T031929929Z")
                 "pi:20260422T031929929Z"))
  (should (equal (my/task-session-parse "pi:20260422T031929929Z")
                 '(:backend "pi" :id "20260422T031929929Z")))
  (should (equal (my/task-session-format "pi" "2026-04-22T03-19-29-929Z")
                 "pi:20260422T031929929Z"))
  (should (equal (my/task-session-parse "pi:2026-04-22T03-19-29-929Z")
                 '(:backend "pi" :id "20260422T031929929Z"))))
(ert-deftest my/task-session-parse-errors-on-invalid-metadata ()
  (should-error (my/task-session-parse "missing-separator")
                :type 'user-error)
  (should-error (my/task-session-parse "unknown:abc")
                :type 'user-error)
  (should-error (my/task-session-parse "pi")
                :type 'user-error)
  (should-error (my/task-session-parse "pi:/tmp/pi-session.jsonl")
                :type 'user-error)
  (should-error (my/task-session-format "pi" "/tmp/pi-session.jsonl")
                :type 'user-error)
  (should-error (my/task-session-format "pi" "")
                :type 'user-error))

(ert-deftest my/task-session-set-and-clear-update-front-matter ()
  (let ((task-file (make-temp-file "my-task-session-front-matter" nil ".md")))
    (unwind-protect
        (progn
          (with-temp-file task-file
            (insert "---\n"
                    "title:        \"Task\"\n"
                    "repo:        brucenunk/home-config\n"
                    "---\n\n"
                    "body\n"))
          (my/task-session-set task-file "pi:20260422T031929929Z")
          (my/task-note-worktree-set task-file "c")
          (should (equal (my/task-session-get task-file)
                         "pi:20260422T031929929Z"))
          (should (equal (my/task-note-worktree-get task-file)
                         "c"))
          (with-temp-buffer
            (insert-file-contents task-file)
            (goto-char (point-min))
            (should (search-forward "session:        pi:20260422T031929929Z" nil t))
            (goto-char (point-min))
            (should (search-forward "worktree:        c" nil t))
            (goto-char (point-min))
            (should (search-forward "repo:        brucenunk/home-config" nil t)))
          (my/task-session-clear task-file)
          (should-not (my/task-session-get task-file))
          (should-not (my/task-note-worktree-get task-file))
          (with-temp-buffer
            (insert-file-contents task-file)
            (goto-char (point-min))
            (should-not (search-forward "session:" nil t))
            (should-not (search-forward "worktree:" nil t))
            (should (search-forward "repo:        brucenunk/home-config" nil t))))
      (delete-file task-file t))))

(ert-deftest my/tasks-map-includes-discard-and-finish ()
  (should (eq (lookup-key my/tasks-map (kbd "D"))
              #'my/task-discard))
  (should (eq (lookup-key my/tasks-map (kbd "F"))
              #'my/task-finish)))

(ert-deftest my/task-resolve-id-prefers-session-buffer-context ()
  (with-temp-buffer
    (setq-local my/task-session-task-id "20260324T103418")
    (should (equal (my/task-resolve-id nil)
                   "20260324T103418"))))

(ert-deftest my/task-session-register-backend-session-persists-formatted-front-matter ()
  (let* ((temp-dir (make-temp-file "my-task-session-register" t))
         (task-file (expand-file-name
                     "20260324T103418==todo--register-session.md"
                     temp-dir)))
    (unwind-protect
        (progn
          (with-temp-file task-file
            (insert "---\n"
                    "title:        \"Task\"\n"
                    "repo:        brucenunk/home-config\n"
                    "---\n\n"
                    "body\n"))
          (should (equal (my/task-session-register-backend-session task-file
                                                                   "pi"
                                                                   "20260422T021929929Z"
                                                                   "b")
                         "pi:20260422T021929929Z"))
          (should (equal (my/task-session-get task-file)
                         "pi:20260422T021929929Z"))
          (should (equal (my/task-note-worktree-get task-file)
                         "b"))
          (should (equal (my/task-session-register-backend-session task-file
                                                                   "pi"
                                                                   "20260422T031929929Z"
                                                                   "c")
                         "pi:20260422T031929929Z"))
          (should (equal (my/task-session-get task-file)
                         "pi:20260422T031929929Z"))
          (should (equal (my/task-note-worktree-get task-file)
                         "c"))
          (should-error (my/task-session-register-backend-session
                         task-file
                         "pi"
                         "/Users/jamesl/.pi/agent/sessions/--Users-jamesl-work-brucenunk-home-config-d--/2026.jsonl")
                        :type 'user-error)
          (should (equal (my/task-note-worktree-get task-file)
                         "c"))
          (should (equal (my/task-session-register-backend-session task-file
                                                                   "pi"
                                                                   "20260422T041929929Z"
                                                                   "c")
                         "pi:20260422T041929929Z"))
          (should (equal (my/task-session-get task-file)
                         "pi:20260422T041929929Z"))
          (should (equal (my/task-note-worktree-get task-file)
                         "c")))
      (delete-directory temp-dir t))))

(ert-deftest my/task-select-marks-wip-without-repair ()
  (let ((task-file "/tmp/20260324T103418==todo--review-lisp.md"))
    (cl-letf (((symbol-function 'my/task-todo-list)
               (lambda ()
                 (list task-file)))
              ((symbol-function 'my/task-status)
               (lambda (_task)
                 "todo"))
              ((symbol-function 'my/task-index-entry)
               (lambda (task-id)
                 (should (equal task-id "20260324T103418"))
                 (list :task-id task-id :worktree "/tmp/a/")))
              ((symbol-function 'denote-retrieve-title-value)
               (lambda (&rest _)
                 "Review lisp"))
              ((symbol-function 'denote-filetype-heuristics)
               (lambda (&rest _)
                 'markdown-yaml))
              ((symbol-function 'completing-read)
               (lambda (_prompt candidates &rest _)
                 (should (equal (caar candidates) "Review lisp [wip]"))
                 (caar candidates))))
      (should (equal (my/task-select) "20260324T103418")))))

(ert-deftest my/task-select-stays-on-cached-state-without-live-git ()
  (let ((task-a "/tmp/20260324T103418==todo--task-a.md")
        (task-b "/tmp/20260324T103419==todo--task-b.md"))
    (cl-letf (((symbol-function 'my/task-todo-list)
               (lambda ()
                 (list task-a task-b)))
              ((symbol-function 'my/task-status)
               (lambda (_task)
                 "todo"))
              ((symbol-function 'my/task-index-entry)
               (lambda (task-id)
                 (and (equal task-id "20260324T103418")
                      (list :task-id task-id :worktree "/tmp/a/"))))
              ((symbol-function 'my/worktree-list-for-repo)
               (lambda (&rest _args)
                 (ert-fail "task picker should not perform live git scans")))
              ((symbol-function 'denote-retrieve-title-value)
               (lambda (file &rest _)
                 (cond
                  ((equal file task-a) "Task A")
                  ((equal file task-b) "Task B"))))
              ((symbol-function 'denote-filetype-heuristics)
               (lambda (&rest _)
                 'markdown-yaml))
              ((symbol-function 'completing-read)
               (lambda (_prompt candidates &rest _)
                 (should (equal (mapcar #'car candidates)
                                '("Task A [wip]" "Task B")))
                 "Task A [wip]")))
      (should (equal (my/task-select) "20260324T103418")))))

(ert-deftest my/task-pickup-always-prompts-when-called-interactively ()
  (let (captured)
    (cl-letf (((symbol-function 'my/task-select)
               (lambda ()
                 "20260324T103418"))
              ((symbol-function 'called-interactively-p)
               (lambda (&rest _)
                 t))
              ((symbol-function 'my/task--call-session)
               (lambda (fn &rest args)
                 (setq captured (cons fn args)))))
      (let ((current-prefix-arg nil))
        (call-interactively #'my/task-pickup))
      (should (equal captured
                     '(my/task-session-command-pickup
                       "20260324T103418"
                       :launch-config nil
                       :advanced-options nil
                       :interactive-p t))))))

(ert-deftest my/task-pickup-noninteractive-keeps-explicit-task ()
  (let (captured)
    (cl-letf (((symbol-function 'called-interactively-p)
               (lambda (&rest _)
                 nil))
              ((symbol-function 'my/task--call-session)
               (lambda (fn &rest args)
                 (setq captured (cons fn args)))))
      (my/task-pickup "20260324T103418")
      (should (equal captured
                     '(my/task-session-command-pickup
                       "20260324T103418"
                       :launch-config nil
                       :advanced-options nil
                       :interactive-p nil))))))

(ert-deftest my/task-discard-summary-uses-live-worktrees-for-wip-guard ()
  (let ((task-file "/tmp/20260324T103418==todo--task-a.md"))
    (cl-letf (((symbol-function 'my/task-status)
               (lambda (_task)
                 "todo"))
              ((symbol-function 'my/task-note-owner-repo)
               (lambda (_task-file)
                 '("brucenunk" . "home-config")))
              ((symbol-function 'my/worktree-list-for-repo)
               (lambda (_owner _repo)
                 (list (list :path "/Users/jamesl/work/brucenunk/home-config/a/"
                             :branch "jamesl-20260324T103418"
                             :detached nil))))
              ((symbol-function 'my/task--branch-task-id)
               (lambda (branch)
                 (and (string-prefix-p "jamesl-" branch)
                      (string-remove-prefix "jamesl-" branch)))))
      (should (equal (my/task--discard-summary (list task-file))
                     '(:task-ids ("20260324T103418")
                       :wip-task-ids ("20260324T103418")
                       :plain-task-ids nil
                       :invalid-task-ids nil))))))

(ert-deftest my/task-discard-summary-treats-detached-closeout-risk-as-wip ()
  (let ((task-file "/tmp/20260324T103418==todo--task-a.md"))
    (cl-letf (((symbol-function 'my/task-status)
               (lambda (_task)
                 "todo"))
              ((symbol-function 'my/task-note-owner-repo)
               (lambda (_task-file)
                 '("brucenunk" . "home-config")))
              ((symbol-function 'my/worktree-list-for-repo)
               (lambda (_owner _repo)
                 nil))
              ((symbol-function 'my/worktree-repair-closeout-state)
               (lambda (_task-id)
                 '(:worktree nil
                   :blocked-reason unattributed-detached-worktrees
                   :ambiguous-worktrees ("/tmp/e/")))))
      (should (equal (my/task--discard-summary (list task-file))
                     '(:task-ids ("20260324T103418")
                       :wip-task-ids ("20260324T103418")
                       :plain-task-ids nil
                       :invalid-task-ids nil))))))

(ert-deftest my/task-state-notify-runs-public-hook ()
  (let (events my/task-state-change-functions)
    (add-hook 'my/task-state-change-functions
              (lambda (event)
                (push event events)))
    (my/task-state-notify "20260324T103418" 'wip :changes '(:active) :active t)
    (should (= (length events) 1))
    (let ((event (car events)))
      (should (equal (plist-get event :task-id) "20260324T103418"))
      (should (eq (plist-get event :source) 'wip))
      (should (equal (plist-get event :changes) '(:active)))
      (should (plist-get event :active)))))

(ert-deftest my/task-todo-summary-counts-current-todo-list ()
  (let ((my/task--todo-summary-count nil)
        (my/task--todo-summary-directory nil)
        (my/task--todo-summary-dirty t)
        (todo-list-calls 0))
    (cl-letf (((symbol-function 'my/task-todo-list)
               (lambda ()
                 (setq todo-list-calls (1+ todo-list-calls))
                 (list "/tmp/20260324T103418==todo--a.md"
                       "/tmp/20260324T103419==todo--b.md"))))
      (let ((summary-a (my/task-todo-summary))
            (summary-b (my/task-todo-summary)))
        (should (= todo-list-calls 1))
        (should (equal summary-a summary-b))
        (should (= summary-a 2))))))

(ert-deftest my/task-notify-note-status-change-invalidates-summary-and-broadcasts ()
  (let ((my/task--todo-summary-dirty nil)
        event)
    (cl-letf (((symbol-function 'denote-retrieve-filename-identifier)
               (lambda (file)
                 (pcase file
                   ("/tmp/20260324T103419==todo--b.md" "20260324T103419"))))
              ((symbol-function 'my/task-state-notify)
               (lambda (&rest args)
                 (setq event args))))
      (my/task--notify-note-status-change "/tmp/20260324T103419==todo--b.md" "todo")
      (should my/task--todo-summary-dirty)
      (should (equal event
                     '("20260324T103419" task-note
                       :changes (:status)
                       :status "todo"
                       :revert-buffers t
                       :file "/tmp/20260324T103419==todo--b.md"))))))

(ert-deftest my/task-todo-summary-rescans-after-invalidation ()
  (let ((my/task--todo-summary-count nil)
        (my/task--todo-summary-directory nil)
        (my/task--todo-summary-dirty t)
        (todo-files '("/tmp/20260324T103418==todo--a.md"))
        (todo-list-calls 0))
    (cl-letf (((symbol-function 'my/task-todo-list)
               (lambda ()
                 (setq todo-list-calls (1+ todo-list-calls))
                 todo-files))
              ((symbol-function 'denote-retrieve-filename-identifier)
               (lambda (_file)
                 "20260324T103419"))
              ((symbol-function 'my/task-state-notify)
               (lambda (&rest _args)
                 nil)))
      (should (= (my/task-todo-summary) 1))
      (setq todo-files '("/tmp/20260324T103418==todo--a.md"
                         "/tmp/20260324T103419==todo--b.md"))
      (my/task--notify-note-status-change "/tmp/20260324T103419==todo--b.md" "todo")
      (should (= (my/task-todo-summary) 2))
      (should (= todo-list-calls 2)))))

(ert-deftest my/task-structured-template-maps-to-note-shape ()
  (should (eq (my/task--workflow-template "task") 'task-workflow-v3))
  (should (eq (my/task--workflow-template "task-workflow-v3") 'task-workflow-v3))
  (should (eq (my/task--workflow-template "bump-nix") 'empty))
  (should (eq (my/task--workflow-template "none") 'empty))
  (should (eq (my/task--workflow-template nil) 'empty)))

(ert-deftest my/task-autonomous-workflows-follow-configured-choices ()
  (should (equal (my/task-autonomous-workflows) '("bump-nix")))
  (let ((my/task-workflows '("task" "example-workflow" "none")))
    (should (equal (my/task-autonomous-workflows) '("example-workflow")))))

(ert-deftest my/task-read-workflow-defaults-to-task-without-prefix ()
  (cl-letf (((symbol-function 'completing-read)
             (lambda (&rest _args)
               (ert-fail "default workflow path should not prompt"))))
    (should (equal (my/task--read-workflow nil) "task"))))

(ert-deftest my/task-read-workflow-prompts-on-extended-path ()
  (cl-letf (((symbol-function 'completing-read)
             (lambda (&rest _args)
               "bump-nix")))
    (should (equal (my/task--read-workflow t) "bump-nix"))))

(ert-deftest my/task-todo-add-notifies-status-change ()
  (let (notified buffer-file-name
                 (denote-templates nil))
    (cl-letf (((symbol-function 'make-directory) (lambda (&rest _) nil))
              ((symbol-function 'denote)
               (lambda (&rest _)
                 (setq buffer-file-name "/tmp/20260324T103418==todo--new-task.md")))
              ((symbol-function 'my/task--front-matter-set) (lambda (&rest _) nil))
              ((symbol-function 'save-buffer) (lambda () nil))
              ((symbol-function 'kill-buffer) (lambda (&rest _) nil))
              ((symbol-function 'my/task-state-notify)
               (lambda (&rest args)
                 (setq notified args))))
      (should (equal (my/task-todo-add "brucenunk" "home-config" "New task" nil)
                     "/tmp/20260324T103418==todo--new-task.md"))
      (should (equal notified
                     '("20260324T103418" task-note
                       :changes (:status)
                       :status "todo"
                       :revert-buffers t
                       :file "/tmp/20260324T103418==todo--new-task.md"))))))

(ert-deftest my/task-todo-add-creates-in-shared-task-root ()
  (let (created-dir denote-dir buffer-file-name)
    (cl-letf (((symbol-function 'make-directory)
               (lambda (dir &rest _args)
                 (setq created-dir dir)))
              ((symbol-function 'denote)
               (lambda (&rest _args)
                 (setq denote-dir denote-directory)
                 (setq buffer-file-name "/tmp/20260324T103418==todo--new-task.md")))
              ((symbol-function 'my/task--front-matter-set) (lambda (&rest _) nil))
              ((symbol-function 'save-buffer) (lambda () nil))
              ((symbol-function 'kill-buffer) (lambda (&rest _) nil))
              ((symbol-function 'my/task-state-notify) (lambda (&rest _) nil)))
      (my/task-todo-add "brucenunk" "home-config" "New task" nil)
      (should (equal created-dir (expand-file-name "~/work/tasks/")))
      (should (equal denote-dir (expand-file-name "~/work/tasks/"))))))

(ert-deftest my/task-todo-add-defaults-to-structured-task-when-workflow-omitted ()
  (let (denote-call front-matter-calls buffer-file-name
        (denote-templates '((task-workflow-v3 . "structured")
                            (empty . ""))))
    (cl-letf (((symbol-function 'make-directory) (lambda (&rest _) nil))
              ((symbol-function 'denote)
               (lambda (&rest args)
                 (setq denote-call args)
                 (setq buffer-file-name "/tmp/20260324T103418==todo--new-task.md")))
              ((symbol-function 'my/task--front-matter-set)
               (lambda (&rest args)
                 (push args front-matter-calls)))
              ((symbol-function 'save-buffer) (lambda () nil))
              ((symbol-function 'kill-buffer) (lambda (&rest _) nil))
              ((symbol-function 'my/task-state-notify) (lambda (&rest _) nil)))
      (my/task-todo-add "brucenunk" "home-config" "Quick task" nil)
      (should (eq (nth 5 denote-call) 'task-workflow-v3))
      (should (member '("skill" "task-workflow-v3") front-matter-calls))
      (should (member '("repo" "brucenunk/home-config") front-matter-calls))
      (should-not (member '("owner" "brucenunk") front-matter-calls)))))

(ert-deftest my/task-todo-add-uses-structured-task-template ()
  (let (denote-call front-matter-calls buffer-file-name
        (denote-templates '((task-workflow-v3 . "workflow"))))
    (cl-letf (((symbol-function 'make-directory) (lambda (&rest _) nil))
              ((symbol-function 'denote)
               (lambda (&rest args)
                 (setq denote-call args)
                 (setq buffer-file-name "/tmp/20260324T103418==todo--new-task.md")))
              ((symbol-function 'my/task--front-matter-set)
               (lambda (&rest args)
                 (push args front-matter-calls)))
              ((symbol-function 'save-buffer) (lambda () nil))
              ((symbol-function 'kill-buffer) (lambda (&rest _) nil))
              ((symbol-function 'my/task-state-notify) (lambda (&rest _) nil)))
      (my/task-todo-add "brucenunk" "home-config" "Workflow task" "task")
      (should (eq (nth 5 denote-call) 'task-workflow-v3))
      (should (member '("skill" "task-workflow-v3") front-matter-calls)))))

(ert-deftest my/task-todo-add-interactive-default-uses-structured-task ()
  (let (denote-call front-matter-calls buffer-file-name
        (denote-templates '((task-workflow-v3 . "workflow"))))
    (cl-letf (((symbol-function 'called-interactively-p)
               (lambda (&rest _args)
                 t))
              ((symbol-function 'my/repo-list)
               (lambda ()
                 '(("brucenunk" . "home-config"))))
              ((symbol-function 'completing-read)
               (lambda (prompt collection &rest _args)
                 (pcase prompt
                   ("Repo: " (car collection))
                   (_ (ert-fail (format "unexpected prompt: %s" prompt)))))
              )
              ((symbol-function 'denote-subdirectory-prompt) (lambda () nil))
              ((symbol-function 'read-string) (lambda (&rest _) "Interactive task"))
              ((symbol-function 'make-directory) (lambda (&rest _) nil))
              ((symbol-function 'denote)
               (lambda (&rest args)
                 (setq denote-call args)
                 (setq buffer-file-name "/tmp/20260324T103418==todo--interactive-task.md")))
              ((symbol-function 'my/task--front-matter-set)
               (lambda (&rest args)
                 (push args front-matter-calls)))
              ((symbol-function 'save-buffer) (lambda () nil))
              ((symbol-function 'my/task-state-notify) (lambda (&rest _) nil)))
      (let ((current-prefix-arg nil))
        (my/task-todo-add nil nil nil nil current-prefix-arg))
      (should (eq (nth 5 denote-call) 'task-workflow-v3))
      (should (member '("skill" "task-workflow-v3") front-matter-calls)))))

(ert-deftest my/task-todo-add-interactive-c-u-allows-direct-skills ()
  (let (denote-call front-matter-calls buffer-file-name
        (denote-templates '((task-workflow-v3 . "workflow")
                            (empty . ""))))
    (cl-letf (((symbol-function 'called-interactively-p)
               (lambda (&rest _args)
                 t))
              ((symbol-function 'my/repo-list)
               (lambda ()
                 '(("brucenunk" . "home-config"))))
              ((symbol-function 'completing-read)
               (lambda (prompt collection &rest _args)
                 (pcase prompt
                   ("Repo: " (car collection))
                   ("Workflow: " "bump-nix")
                   (_ (ert-fail (format "unexpected prompt: %s" prompt)))))
              )
              ((symbol-function 'denote-subdirectory-prompt) (lambda () nil))
              ((symbol-function 'read-string) (lambda (&rest _) "Bump task"))
              ((symbol-function 'make-directory) (lambda (&rest _) nil))
              ((symbol-function 'denote)
               (lambda (&rest args)
                 (setq denote-call args)
                 (setq buffer-file-name "/tmp/20260324T103418==todo--bump-task.md")))
              ((symbol-function 'my/task--front-matter-set)
               (lambda (&rest args)
                 (push args front-matter-calls)))
              ((symbol-function 'save-buffer) (lambda () nil))
              ((symbol-function 'my/task-state-notify) (lambda (&rest _) nil)))
      (let ((current-prefix-arg '(4)))
        (my/task-todo-add nil nil nil nil current-prefix-arg))
      (should (eq (nth 5 denote-call) 'empty))
      (should (member '("skill" "bump-nix") front-matter-calls)))))

(ert-deftest my/task-todo-add-uses-empty-template-for-direct-skills ()
  (let (denote-call front-matter-calls buffer-file-name
        (denote-templates '((task-workflow-v3 . "structured")
                            (empty . ""))))
    (cl-letf (((symbol-function 'make-directory) (lambda (&rest _) nil))
              ((symbol-function 'denote)
               (lambda (&rest args)
                 (setq denote-call args)
                 (setq buffer-file-name "/tmp/20260324T103418==todo--new-task.md")))
              ((symbol-function 'my/task--front-matter-set)
               (lambda (&rest args)
                 (push args front-matter-calls)))
              ((symbol-function 'save-buffer) (lambda () nil))
              ((symbol-function 'kill-buffer) (lambda (&rest _) nil))
              ((symbol-function 'my/task-state-notify) (lambda (&rest _) nil)))
      (my/task-todo-add "brucenunk" "home-config" "Skill task" "bump-nix")
      (should (eq (nth 5 denote-call) 'empty))
      (should (member '("skill" "bump-nix") front-matter-calls)))))

(ert-deftest my/task-todo-add-interactive-errors-when-repo-index-is-empty ()
  (let ((denote-templates nil))
    (cl-letf (((symbol-function 'called-interactively-p)
               (lambda (&rest _args)
                 t))
              ((symbol-function 'my/repo-list)
               (lambda ()
                 nil)))
      (should-error (my/task-todo-add nil nil nil nil)
                    :type 'user-error))))

(ert-deftest my/task-mark-todo-notifies-status-change ()
  (let (notified)
    (cl-letf (((symbol-function 'my/task--rename-in-task-repo)
               (lambda (&rest _)
                 "/tmp/20260324T103418==todo--renamed.md"))
              ((symbol-function 'my/task-state-notify)
               (lambda (&rest args)
                 (setq notified args))))
      (should (equal (my/task-mark-todo "/tmp/20260324T103418==done--renamed.md")
                     "/tmp/20260324T103418==todo--renamed.md"))
      (should (equal notified
                     '("20260324T103418" task-note
                       :changes (:status)
                       :status "todo"
                       :revert-buffers t
                       :file "/tmp/20260324T103418==todo--renamed.md"))))))

(ert-deftest my/task-finish-rejects-non-todo-tasks ()
  (cl-letf (((symbol-function 'my/task--resolve-id)
             (lambda (_task)
               "20260324T103418"))
            ((symbol-function 'my/task-status)
             (lambda (_task)
               "discarded"))
            ((symbol-function 'my/task-finish-run)
              (lambda (&rest _args)
                (ert-fail "direct finish should not run for non-todo tasks"))))
    (should-error (my/task-finish "20260324T103418")
                  :type 'user-error)))

(ert-deftest my/task-finish-calls-direct-closeout ()
  (let (finished-task)
    (cl-letf (((symbol-function 'my/task--resolve-id)
               (lambda (_task)
                 "20260324T103418"))
              ((symbol-function 'my/task-status)
               (lambda (_task)
                 "todo"))
              ((symbol-function 'my/task-finish-run)
               (lambda (task-id)
                 (setq finished-task task-id))))
      (my/task-finish "20260324T103418")
      (should (equal finished-task "20260324T103418")))))

(ert-deftest my/task-discard-confirms-and-runs-closeout ()
  (let (discarded-task)
    (cl-letf (((symbol-function 'my/task-status)
               (lambda (_task)
                 "todo"))
              ((symbol-function 'my/task-index-entry)
               (lambda (_task-id)
                 (list :task-id "20260324T103418" :worktree "/tmp/a/")))
              ((symbol-function 'yes-or-no-p)
               (lambda (prompt)
                 (should (string-match-p "Discard 1 task" prompt))
                 t))
              ((symbol-function 'my/task-discard-run)
               (lambda (task-id)
                 (setq discarded-task task-id))))
      (my/task-discard "20260324T103418")
      (should (equal discarded-task "20260324T103418")))))

(ert-deftest my/task-finish-run-destroys-worktree-before-marking-done ()
  (let (operations index-removed notified)
    (cl-letf (((symbol-function 'denote-get-path-by-id)
               (lambda (_task-id)
                 "/tmp/20260324T103418==todo--task.md"))
              ((symbol-function 'my/task-status)
               (lambda (_task)
                 "todo"))
              ((symbol-function 'my/task-branch)
               (lambda (_task-id)
                 "jamesl-20260324T103418"))
              ((symbol-function 'my/task-finish--closeout-worktree-state)
               (lambda (_task-id)
                 '(:worktree "/tmp/worktree/" :mode attached)))
              ((symbol-function 'my/task-finish--repo-location)
               (lambda (_task-file)
                 '("brucenunk" "home-config" "/tmp/default/")))
              ((symbol-function 'my/task-finish--reset-worktree)
               (lambda (worktree)
                 (push (list 'reset worktree) operations)))
              ((symbol-function 'my/task-finish--call-session)
               (lambda (fn &rest args)
                 (push (cons fn args) operations)))
              ((symbol-function 'my/task-finish--delete-branch)
               (lambda (task-id branch default-wt)
                 (push (list 'delete task-id branch default-wt) operations)))
              ((symbol-function 'my/task-finish--refresh-task-buffer)
               (lambda (_task-file)
                 (push '(refresh) operations)))
              ((symbol-function 'my/task-mark-done)
               (lambda (_task-file)
                 (push '(mark-done) operations)
                 "/tmp/20260324T103418==done--task.md"))
              ((symbol-function 'my/task-finish--check-off-deps)
               (lambda (task-id)
                 (push (list 'deps task-id) operations)))
              ((symbol-function 'my/task-index-remove)
               (lambda (task-id)
                 (setq index-removed task-id)
                 (push (list 'index-remove task-id) operations)))
              ((symbol-function 'my/task-finish--notify)
               (lambda (&rest args)
                 (setq notified args)))
              ((symbol-function 'denote-retrieve-filename-title)
               (lambda (_file)
                 "Task"))
              ((symbol-function 'message)
               (lambda (&rest _args)
                 nil)))
      (my/task-finish-run "20260324T103418")
      (should (equal index-removed "20260324T103418"))
      (should
       (equal (nreverse operations)
              '((reset "/tmp/worktree/")
                (my/task-session-release "20260324T103418" "/tmp/worktree/")
                (delete "20260324T103418" "jamesl-20260324T103418" "/tmp/default/")
                (refresh)
                (mark-done)
                (deps "20260324T103418")
                (index-remove "20260324T103418"))))
      (should
       (equal notified
              '("20260324T103418"
                :changes (:worktree :active)
                :worktree nil
                :active nil))))))

(ert-deftest my/task-discard-run-clears-buffer-before_release_and_skips_second_rename ()
  (let (operations index-removed)
    (cl-letf (((symbol-function 'denote-get-path-by-id)
               (lambda (_task-id)
                 "/tmp/20260324T103418==discarded--task.md"))
              ((symbol-function 'my/task-status)
               (lambda (_task)
                 "discarded"))
              ((symbol-function 'my/task-branch)
               (lambda (_task-id)
                 "jamesl-20260324T103418"))
              ((symbol-function 'my/task-finish--closeout-worktree-state)
               (lambda (_task-id)
                 '(:worktree "/tmp/worktree/" :mode attached)))
              ((symbol-function 'my/task-finish--repo-location)
               (lambda (_task-file)
                 '("brucenunk" "home-config" "/tmp/default/")))
              ((symbol-function 'my/task-finish--reset-worktree)
               (lambda (worktree)
                 (push (list 'reset worktree) operations)))
              ((symbol-function 'my/task-finish--call-session)
               (lambda (fn &rest args)
                 (push (cons fn args) operations)))
              ((symbol-function 'my/task-finish--delete-branch)
               (lambda (task-id branch default-wt)
                 (push (list 'delete task-id branch default-wt) operations)))
              ((symbol-function 'my/task-mark-discarded)
               (lambda (&rest _args)
                 (ert-fail "already-discarded task should not be renamed again")))
              ((symbol-function 'my/task-index-remove)
               (lambda (task-id)
                 (setq index-removed task-id)
                 (push (list 'index-remove task-id) operations)))
              ((symbol-function 'my/task-finish--notify)
               (lambda (&rest _args)
                 nil))
              ((symbol-function 'denote-retrieve-filename-title)
               (lambda (_file)
                 "Task"))
              ((symbol-function 'message)
               (lambda (&rest _args)
                 nil)))
      (my/task-discard-run "20260324T103418")
      (should (equal index-removed "20260324T103418"))
      (should
       (equal (nreverse operations)
              '((my/task-session-clear-buffer "20260324T103418")
                (reset "/tmp/worktree/")
                (my/task-session-release "20260324T103418" "/tmp/worktree/")
                (delete "20260324T103418" "jamesl-20260324T103418" "/tmp/default/")
                (index-remove "20260324T103418")))))))

(ert-deftest my/task-discard-run-marks_todo_task_discarded_after_cleanup ()
  (let (operations)
    (cl-letf (((symbol-function 'denote-get-path-by-id)
               (lambda (_task-id)
                 "/tmp/20260324T103418==todo--task.md"))
              ((symbol-function 'my/task-status)
               (lambda (_task)
                 "todo"))
              ((symbol-function 'my/task-branch)
               (lambda (_task-id)
                 "jamesl-20260324T103418"))
              ((symbol-function 'my/task-finish--closeout-worktree-state)
               (lambda (_task-id)
                 '(:worktree nil :mode none)))
              ((symbol-function 'my/task-finish--repo-location)
               (lambda (_task-file)
                 '("brucenunk" "home-config" "/tmp/default/")))
              ((symbol-function 'my/task-finish--reset-worktree)
               (lambda (_worktree)
                 (push '(reset) operations)))
              ((symbol-function 'my/task-finish--call-session)
               (lambda (fn &rest args)
                 (push (cons fn args) operations)))
              ((symbol-function 'my/task-finish--delete-branch)
               (lambda (&rest _args)
                 (push '(delete) operations)))
              ((symbol-function 'my/task-finish--refresh-task-buffer)
               (lambda (_task-file)
                 (push '(refresh) operations)))
              ((symbol-function 'my/task-mark-discarded)
               (lambda (_task-file)
                 (push '(mark-discarded) operations)
                 "/tmp/20260324T103418==discarded--task.md"))
              ((symbol-function 'my/task-index-remove)
               (lambda (_task-id)
                 (push '(index-remove) operations)))
              ((symbol-function 'my/task-finish--notify)
               (lambda (&rest _args)
                 nil))
              ((symbol-function 'denote-retrieve-filename-title)
               (lambda (_file)
                 "Task"))
              ((symbol-function 'message)
               (lambda (&rest _args)
                 nil)))
      (my/task-discard-run "20260324T103418")
      (should
       (equal (nreverse operations)
              '((my/task-session-clear-buffer "20260324T103418")
                (refresh)
                (mark-discarded)
                (reset)
                (my/task-session-release "20260324T103418" nil)
                (delete)
                (index-remove)))))))

(ert-deftest my/task-discard-run-aborts-before_teardown_when_note_transition_fails ()
  (let (operations)
    (cl-letf (((symbol-function 'denote-get-path-by-id)
               (lambda (_task-id)
                 "/tmp/20260324T103418==todo--task.md"))
              ((symbol-function 'my/task-status)
               (lambda (_task)
                 "todo"))
              ((symbol-function 'my/task-branch)
               (lambda (_task-id)
                 "jamesl-20260324T103418"))
              ((symbol-function 'my/task-finish--closeout-worktree-state)
               (lambda (_task-id)
                 '(:worktree "/tmp/worktree/" :mode attached)))
              ((symbol-function 'my/task-finish--repo-location)
               (lambda (_task-file)
                 '("brucenunk" "home-config" "/tmp/default/")))
              ((symbol-function 'my/task-finish--call-session)
               (lambda (fn &rest args)
                 (push (cons fn args) operations)))
              ((symbol-function 'my/task-finish--refresh-task-buffer)
               (lambda (_task-file)
                 (push '(refresh) operations)))
              ((symbol-function 'my/task-mark-discarded)
               (lambda (_task-file)
                 (push '(mark-discarded) operations)
                 (error "rename failed")))
              ((symbol-function 'my/task-finish--reset-worktree)
               (lambda (&rest _args)
                 (push '(reset) operations)
                 (ert-fail "discard teardown should not run after rename failure")))
              ((symbol-function 'my/task-finish--delete-branch)
               (lambda (&rest _args)
                 (push '(delete) operations)
                 (ert-fail "branch deletion should not run after rename failure")))
              ((symbol-function 'my/task-index-remove)
               (lambda (_task-id)
                 (push '(index-remove) operations)
                 (ert-fail "index removal should not run after rename failure")))
              ((symbol-function 'my/task-finish--notify)
               (lambda (&rest _args)
                 (ert-fail "notifications should not run after rename failure")))
              ((symbol-function 'message)
               (lambda (&rest _args)
                 nil)))
      (should-error (my/task-discard-run "20260324T103418")
                    :type 'error)
      (should
       (equal (nreverse operations)
              '((my/task-session-clear-buffer "20260324T103418")
                (refresh)
                (mark-discarded)))))))

(ert-deftest my/task-discard-run-fails-closed-on-ambiguous-detached-worktree ()
  (let (operations)
    (cl-letf (((symbol-function 'denote-get-path-by-id)
               (lambda (_task-id)
                 "/tmp/20260324T103418==todo--task.md"))
              ((symbol-function 'my/task-status)
               (lambda (_task)
                 "todo"))
              ((symbol-function 'my/task-branch)
               (lambda (_task-id)
                 "jamesl-20260324T103418"))
              ((symbol-function 'my/task-finish--closeout-worktree-state)
               (lambda (_task-id)
                 (user-error "Cannot close out task 20260324T103418 safely (unattributed-detached-worktrees): /tmp/e/")))
              ((symbol-function 'my/task-finish--refresh-task-buffer)
               (lambda (_task-file)
                 (push '(refresh) operations)
                 (ert-fail "closeout should fail before note transition")))
              ((symbol-function 'my/task-mark-discarded)
               (lambda (_task-file)
                 (push '(mark-discarded) operations)
                 (ert-fail "closeout should fail before note transition")))
              ((symbol-function 'my/task-finish--call-session)
               (lambda (fn &rest args)
                 (push (cons fn args) operations)))
              ((symbol-function 'message)
               (lambda (&rest _args)
                 nil)))
      (should-error (my/task-discard-run "20260324T103418")
                    :type 'user-error)
      (should-not operations))))

(ert-deftest my/git-in-merge-or-rebase-p-resolves-linked-worktree-git-dir ()
  (require 'my-git)
  (let ((git-dir (make-temp-file "my-git-dir" t)))
    (unwind-protect
        (progn
          (with-temp-file (expand-file-name "MERGE_HEAD" git-dir)
            (insert "merge"))
          (cl-letf (((symbol-function 'my/git-run-in-dir)
                     (lambda (_dir &rest _args)
                       (cons 0 (concat git-dir "\n")))))
            (should (my/git-in-merge-or-rebase-p "/tmp/worktree"))))
      (delete-directory git-dir t))))

(ert-deftest my/task-startup-recover-index-async-backfills-live-attached-worktrees ()
  (my/task-index-test--with-isolated-index
    (let ((callback-result :unset)
          (notifications nil)
          (my/task--startup-recovery-running nil)
          (my/task--startup-recovery-callbacks nil))
      (my/task-index-put "20260324T103419" (list :worktree "/tmp/reused/"))
      (cl-letf (((symbol-function 'run-with-idle-timer)
                 (lambda (_secs _repeat fn &rest _args)
                   (funcall fn)
                   'timer))
                ((symbol-function 'file-directory-p)
                 (lambda (path)
                   (member path '("/tmp/a/" "/tmp/reused/"))))
                ((symbol-function 'my/git-branch)
                 (lambda (path)
                   (pcase path
                     ("/tmp/a/" "jamesl-20260324T103418")
                     ("/tmp/reused/" "jamesl-20260324T999999"))))
                ((symbol-function 'my/task-todo-list)
                 (lambda ()
                   '("/tmp/20260324T103418==todo--task.md")))
                ((symbol-function 'my/task--live-worktree-table)
                 (lambda (_task-files)
                   (let ((table (make-hash-table :test 'equal)))
                     (puthash "20260324T103418" "/tmp/a/" table)
                     table)))
                ((symbol-function 'my/task-state-notify)
                 (lambda (task-id source &rest props)
                   (push (append (list :task-id task-id :source source) props)
                         notifications))))
        (my/task-startup-recover-index-async
         :on-complete (lambda (result)
                        (setq callback-result result)))
        (should (equal (my/task-index-worktree "20260324T103418")
                       "/tmp/a/"))
        (should-not (my/task-index-worktree "20260324T103419"))
        (should (equal callback-result
                       '(:recovered ("20260324T103419" "20260324T103418") :failed nil)))
        (should (= (length notifications) 2))
        (should-not my/task--startup-recovery-running)
        (should-not my/task--startup-recovery-callbacks)))))

(provide 'my-task-tests)
;;; my-task-tests.el ends here
